Repository decentdao/decent-app, pull requests merged in 2022-05, with the labels that each got.

#115 Create Dao Form Updates
  src/components/DAOs/New/DAODetails.tsx
  src/components/DAOs/New/GovernanceDetails.tsx
  src/components/DAOs/New/TokenAllocationInput.tsx
  src/components/DAOs/New/TokenAllocations.tsx
  src/components/DAOs/New/TokenDetails.tsx
  src/components/DAOs/New/index.tsx
  src/components/ui/H1.tsx
  src/components/ui/forms/Button.tsx
  src/components/ui/forms/Input.tsx
  tailwind.config.js
Labels: bug, ui

#117 Delegate vote update
  src/components/DAOs/DAO/DelegateVote.tsx
  src/components/ui/forms/Input.tsx
Labels: ui

#118 Proposals Update
  src/components/DAOs/DAO/Proposals/ProposalCard.tsx
  src/components/ui/ContentBox.tsx
  src/components/ui/StatusBox.tsx
  tailwind.config.js
Labels: ui

#119 Updates Proposal Details UI
  src/components/DAOs/DAO/Proposals/CastVote.tsx
  src/components/DAOs/DAO/Proposals/ProposalCardDetailed.tsx
  src/components/DAOs/DAO/Proposals/ProposalVotes.tsx
  src/components/ui/forms/Button.tsx
Labels: ui

#120 Design Update New Proposal
  src/App.tsx
  src/components/ConnectModal.tsx
  src/components/DAOs/DAO/Proposals/New/Essentials.tsx
  src/components/DAOs/DAO/Proposals/New/Transaction.tsx
  src/components/DAOs/DAO/Proposals/New/Transactions.tsx
  src/components/DAOs/DAO/Proposals/New/index.tsx
  src/components/DAOs/DAO/Proposals/ProposalQueue.tsx
  src/components/DAOs/New/index.tsx
  src/components/ui/Button.tsx
  src/components/ui/CreateDAOInput.tsx
  src/components/ui/Input.tsx
  src/components/ui/InputBox.tsx
  src/components/ui/PrimaryButton.tsx
  src/components/ui/SelectVoteButton.tsx
  src/components/ui/forms/Input.tsx
  tailwind.config.js
Labels: ui

#126 Content Banner Update
  src/components/DAOs/DAO/Proposals/CastVote.tsx
  src/components/DAOs/New/TokenDetails.tsx
  src/components/ui/ContentBanner.tsx
  src/components/ui/svg/Info.tsx
  tailwind.config.js
Labels: ui

#129 Governance Details
  src/components/DAOs/New/GovernanceDetails.tsx
  src/components/ui/forms/Input.tsx
  src/components/ui/svg/Lock.tsx
Labels: ui

#131 Unload DAO
  src/components/DAOs/DAO/index.tsx
  src/daoData/useModuleAddresses.ts
  src/daoData/useProposals.ts
  src/daoData/useTokenData.ts
Labels: bug, data

#133 updates TokenDetails input validations
  src/components/DAOs/New/TokenAllocationInput.tsx
  src/components/DAOs/New/TokenAllocations.tsx
  src/components/DAOs/New/TokenDetails.tsx
  src/components/ui/forms/Input.tsx
  src/daoData/useDeployDAO.ts
  src/hooks/useAddress.ts
Labels: ui

#134 Dao dashboard actions
  src/components/DAOs/DAO/Delegate.tsx
  src/components/DAOs/DAO/Proposals/ProposalCard.tsx
  src/components/DAOs/DAO/Proposals/ProposalsList.tsx
  src/components/DAOs/DAO/Summary.tsx
  src/components/DAOs/DAO/index.tsx
Labels: bug, data

#143 Quick Fix: Pending Screen
  src/components/Pending.tsx
Labels: ui

#150 QuickFix Proposal Responsive Update
  src/components/DAOs/DAO/Delegate.tsx
  src/components/DAOs/DAO/Proposals/ProposalCard.tsx
  src/components/ui/StatusBox.tsx
Labels: ui

#144 Header Mobile update
  src/components/ui/Header/HeaderMenu.tsx
  src/components/ui/Header/MenuItems.tsx
  src/components/ui/Header/index.tsx
Labels: bug, ui

#153 fixes errorMap validation
  src/components/DAOs/New/TokenDetails.tsx
Labels: bug, P1

#156 updates web3Modal to match fractal theme
  src/index.css
  src/web3/providers.ts
Labels: ui

#168 Delegate Vote Address validation
  src/components/DAOs/DAO/Delegate.tsx
Labels: refactor

#178 Dao Loading and error handling
  src/components/DAOs/DAO/index.tsx
  src/components/DAOs/Search/DAOSearch.tsx
  src/components/DAOs/Search/SearchingDAO.tsx
  src/hooks/useAddress.ts
  src/hooks/useSearchDao.ts
Labels: bug, enhancement, ui

#180 Delegate Vote Input Bug Fix
  src/components/DAOs/DAO/Delegate.tsx
Labels: bug, ui

#184 Handle Network Change on DAO Route
  src/components/DAOs/DAO/index.tsx
Labels: bug, P2

#183 Remove errorMap
  src/components/DAOs/DAO/Proposals/New/Transaction.tsx
  src/components/DAOs/DAO/Proposals/New/Transactions.tsx
  src/components/DAOs/DAO/Proposals/New/index.tsx
  src/components/DAOs/New/TokenAllocationInput.tsx
  src/components/DAOs/New/TokenAllocations.tsx
  src/components/DAOs/New/TokenDetails.tsx
  src/daoData/useDeployDAO.ts
Labels: ui

#187 removed unused code
  src/components/DAOs/DAO/Proposals/New/index.tsx
Labels: bug

#203 `stripChars` should strip decimal places too
  src/components/ui/forms/Input.tsx
Labels: bug

#202 Blockchain data context
  src/components/Breadcrumbs.tsx
  src/components/DAOs/DAO/Delegate.tsx
  src/components/DAOs/DAO/Details.tsx
  src/components/DAOs/DAO/Proposals/CastVote.tsx
  src/components/DAOs/DAO/Proposals/New/Transaction.tsx
  src/components/DAOs/DAO/Proposals/New/index.tsx
  src/components/DAOs/DAO/Proposals/ProposalCard.tsx
  src/components/DAOs/DAO/Proposals/ProposalCardDetailed.tsx
  src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
  src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
  src/components/DAOs/DAO/Proposals/ProposalQueue.tsx
  src/components/DAOs/DAO/Proposals/ProposalVotes.tsx
  src/components/DAOs/DAO/Proposals/ProposalsList.tsx
  src/components/DAOs/DAO/index.tsx
  src/components/DAOs/New/TokenAllocationInput.tsx
  src/components/DAOs/New/TokenAllocations.tsx
  src/components/DAOs/New/TokenDetails.tsx
  src/components/DAOs/New/index.tsx
  src/components/DAOs/Search/DAOSearch.tsx
  src/components/DAOs/shared/ConnectWalletToast.tsx
  src/components/ui/EtherscanLink.tsx
  src/components/ui/Header/HeaderMenu.tsx
  src/components/ui/Header/MenuItems.tsx
  src/contexts/blockchainData/blockchainData.ts
  src/contexts/blockchainData/index.tsx
  src/contexts/blockchainData/useCurrentBlockNumber.ts
  src/contexts/blockchainData/useCurrentTimestamp.ts
  src/contexts/daoData/daoData.ts
  src/contexts/daoData/index.tsx
  src/contexts/daoData/useAccessControlAddress.ts
  src/contexts/daoData/useAccessControlContract.ts
  src/contexts/daoData/useDAOContract.ts
  src/contexts/daoData/useDAOName.ts
  src/contexts/daoData/useGovernorModuleContract.ts
  src/contexts/daoData/useModuleAddresses.ts
  src/contexts/daoData/useProposals.ts
  src/contexts/daoData/useSafeRace.ts
  src/contexts/daoData/useTimelockModuleContract.ts
  src/contexts/daoData/useTokenContract.ts
  src/contexts/daoData/useTokenData.ts
  src/contexts/web3Data/chains.tsx
  src/contexts/web3Data/index.tsx
  src/contexts/web3Data/listeners.ts
  src/contexts/web3Data/providers.ts
  src/contexts/web3Data/transactions.ts
  src/hooks/use165Contract.ts
  src/hooks/useAddress.ts
  src/hooks/useAvatar.ts
  src/hooks/useCastVote.ts
  src/hooks/useCreateProposal.ts
  src/hooks/useDelegateVote.ts
  src/hooks/useDeployDAO.ts
  src/hooks/useENSName.ts
  src/hooks/useExecuteTransaction.ts
  src/hooks/useQueueTransaction.ts
  src/index.tsx
Labels: data

#228 styles wallet connect modal
  src/index.css
Labels: ui

#230 BugFix: Token Allocation Validation
  src/components/DAOs/New/TokenAllocationInput.tsx
Labels: bug

#245 Add a bit of top margin to each toast
  src/index.tsx
Labels: ui

#246 Add IPFS dev workflow
  .github/workflows/release-ipfs-dev.yaml
Labels: enhancement

#254 removes extra margin
  src/components/Proposals/CastVote.tsx
  src/components/Proposals/ProposalCardDetailed.tsx
  src/components/Proposals/ProposalDetails.tsx
  src/components/Proposals/ProposalVotes.tsx
Labels: ui

#255 211-Find a Fractal button not aligned
  src/pages/DaoSearch/index.tsx
Labels: ui

#258 removed unneeded copy
  src/components/Proposals/CastVote.tsx
Labels: bug, ui

#277 Show Dao Address in tooltip
  package-lock.json
  package.json
  src/components/Breadcrumbs.tsx
  src/components/ui/TooltipWrapper.tsx
  src/contexts/daoData/daoData.ts
  src/index.css
  tailwind.config.js
Labels: enhancement, ui

#283 disables form after submit
  src/components/ProposalCreate/Transaction.tsx
Labels: bug

#288 Details UI update
  src/components/Breadcrumbs.tsx
  src/components/Dao/Details.tsx
  src/components/ui/svg/Details.tsx
  src/components/ui/svg/Treasury.tsx
Labels: ui

#292 BugFix. Unmounted Component
  src/hooks/useENSName.ts
Labels: bug

#295 resets state when url is manually updated on page
  src/contexts/daoData/treasury/useTreasuryAssets.ts
  src/contexts/daoData/treasury/useTreasuryEvents.ts
Labels: bug
