Repository decentdao/decent-app, pull requests merged in 2022-12, with the labels that each got.

#719 Feature | DAO Dashboard Multisig Transactions
  src/components/ui/badges/Badge.tsx
  src/i18n/locales/en/common.json
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/en/treasury.json
  src/pages/DaoDashboard/Activities/ActivityAddress.tsx
  src/pages/DaoDashboard/Activities/ActivityDescription.tsx
  src/pages/DaoDashboard/Activities/ActivityGovernance.tsx
  src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/hooks/useActivityParser.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/providers/Fractal/constants/state.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/hooks/useGnosisGovernance.ts
  src/providers/Fractal/types/actions.ts
  src/providers/Fractal/types/gnosis.ts
  src/providers/Fractal/types/state.ts
  src/types/activity.ts
Labels: enhancement, ui, V1-Design

#727 Refactor & Update | Adds Governance Card Live Data
  src/hooks/utils/useTimeHelpers.tsx
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/pages/Proposals/index.tsx
  src/pages/Treasury/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/actions.ts
  src/providers/Fractal/constants/state.ts
  src/providers/Fractal/governance/actions.ts
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/governance/reducer.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useGnosisGovernance.ts
  src/providers/Fractal/types/actions.ts
  src/providers/Fractal/types/index.ts
  src/providers/Fractal/types/state.ts
Labels: ui, refactor

#734 Update | Governance State Transactions/Proposals
  src/components/Proposals/ProposalActions/Execute.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/Proposals/ProposalActions/Queue.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/Proposals/ProposalCard.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/ui/modals/DelegateModal.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/components/ui/proposal/ProposalStateBox.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/components/ui/proposal/ProposalTitle.tsx
  src/hooks/DAO/useDAOController.ts
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/hooks/useActivityParser.ts
  src/pages/DaoDashboard/Info/InfoProposals.tsx
  src/pages/ProposalDetails/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/state.ts
  src/providers/Fractal/governance/actions.ts
  src/providers/Fractal/governance/constants.ts
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/governance/reducer.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useProposals.ts
  src/providers/Fractal/types/index.ts
  src/providers/Fractal/types/usul.ts
  src/providers/Fractal/utils/usul.ts
Labels: enhancement, refactor

#742 Update | Add Usul Proposals to Dashboard
  src/components/Proposals/ProposalCard.tsx
  src/components/ui/badges/Badge.tsx
  src/components/ui/containers/ActivityBox.tsx
  src/i18n/locales/en/proposal.json
  src/pages/DaoDashboard/Activities/ActivityCard.tsx
  src/pages/DaoDashboard/Activities/ActivityDescription.tsx
  src/pages/DaoDashboard/Activities/ActivityGovernance.tsx
  src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/utils/usul.ts
  src/types/activity.ts
Labels: enhancement

#757 Votes breakdown total votes casted
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/ui/proposal/ProposalTitle.tsx
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/utils/usul.ts
Labels: enhancement, refactor

#761 Enhancement | Polling safe data
  src/hooks/utils/useUpdateTimer.tsx
  src/providers/Fractal/hooks/useGnosisApiServices.ts
Labels: enhancement

#760 Bug | Fix DAOs loading incorrectly or hanging
  src/hooks/DAO/proposal/useProposals.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/hooks/utils/useUpdateTimer.tsx
  src/pages/ProposalDetails/index.tsx
  src/pages/Proposals/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/actions.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/hooks/useDAOName.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/reducers/gnosis.ts
  src/providers/Fractal/types/actions.ts
  src/providers/Fractal/types/state.ts
Labels: bug, refactor

#758 Update | Safe Proposal Details
  src/components/Activity/ActivityAddress.tsx
  src/components/Activity/ActivityDescription.tsx
  src/components/Activity/ActivityDescriptionGovernance.tsx
  src/components/Activity/ActivityGovernance.tsx
  src/components/ProposalCreate/ProposalDetails.tsx
  src/components/Proposals/MultisigProposalDetails/SignerDetails.tsx
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/Proposals/MultisigProposalDetails/TxDetails.tsx
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/Proposals/ProposalActions/Execute.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/Proposals/ProposalActions/Queue.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/Proposals/ProposalInfo.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/components/ui/ContentBox.tsx
  src/components/ui/EtherscanDisplayNameLink.tsx
  src/components/ui/badges/Badge.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/containers/ActivityBox.tsx
  src/components/ui/containers/InfoBox.tsx
  src/components/ui/containers/TitledInfoBox.tsx
  src/components/ui/modals/ModalBase.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/constants/common.ts
  src/hooks/DAO/proposal/useProposals.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/utils/useAsyncRequest.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/hooks/utils/useUpdateTimer.tsx
  src/i18n/locales/en/proposal.json
  src/pages/DaoDashboard/Activities/index.tsx
  src/pages/ProposalCreate/index.tsx
  src/pages/ProposalDetails/index.tsx
  src/pages/Proposals/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/actions.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useDAOName.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/reducers/gnosis.ts
  src/providers/Fractal/types/actions.ts
  src/providers/Fractal/types/state.ts
  src/providers/Fractal/utils/usul.ts
  src/utils/string.ts
Labels: enhancement, ui, refactor, V1-Design

#789 Update | Supports Module activity on Dashboard
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/Activity/ActivityModule.tsx
  src/components/ui/badges/Badge.tsx
  src/hooks/utils/useParseSafeTxs.tsx
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/en/proposal.json
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/providers/Fractal/governance/types.ts
Labels: bug

#792 Ukrainian translation
  src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx
  src/i18n/LanguageSwitcher.tsx
  src/i18n/index.ts
  src/i18n/locales/en/languages.json
  src/i18n/locales/uk/common.json
  src/i18n/locales/uk/daoCreate.json
  src/i18n/locales/uk/dashboard.json
  src/i18n/locales/uk/languages.json
  src/i18n/locales/uk/menu.json
  src/i18n/locales/uk/modals.json
  src/i18n/locales/uk/proposal.json
  src/i18n/locales/uk/sidebar.json
  src/i18n/locales/uk/transaction.json
  src/i18n/locales/uk/treasury.json
Labels: enhancement

#790 BugFix | Activity and Proposal Sorting
  src/components/Activity/ActivityGovernance.tsx
  src/components/Activity/ActivityModule.tsx
  src/components/Activity/ActivityTreasury.tsx
  src/hooks/utils/useParseSafeTxs.tsx
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/utils/usul.ts
Labels: bug

#795 Update | Adds delay to DAO Creation
  src/hooks/utils/useAsyncRetry.ts
  src/pages/DaoCreate/index.tsx
Labels: bug, enhancement

#809 BugFix | Clean DAO data when not viewing DAO
  src/hooks/DAO/useDAOController.ts
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/reducers/gnosis.ts
Labels: bug

#801 BugFix | Handle duplicate Address allocation error
  src/components/DaoCreator/gnosis/GnosisSignature.tsx
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/components/ProposalCreate/Transaction.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/hooks/safe/useIsSafe.ts
  src/i18n/locales/en/daoCreate.json
Labels: bug

#821 Hotfix | Show correct DAO name on Node Page.
  src/components/ui/cards/DAOInfoCard.tsx
Labels: bug

#840 Update | No account DAO viewing
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/hooks/DAO/useDAOController.ts
  src/pages/Proposals/index.tsx
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
Labels: enhancement

#847 Usul proposal events listeners
  src/components/Activity/ActivityDescriptionGovernance.tsx
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/Activity/ActivityGovernance.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/uk/dashboard.json
  src/providers/Fractal/governance/hooks/useUpdateProposalState.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/types.ts
Labels: P2

#808 Update parameters splitting logic and validation
  src/components/ProposalCreate/Transaction.tsx
  src/components/ProposalCreate/Transactions.tsx
  src/pages/ProposalCreate/index.tsx
  src/types/transaction.ts
  src/utils/dev.ts
Labels: bug
