Repository decentdao/decent-app, pull requests merged in 2022-04, with the labels that each got.

#73 Copied Text Toast
  src/components/ui/CopyToClipboard.tsx
Labels: ui

#79 Place max width on body of 768px
  src/App.tsx
Labels: ui

#71 Header Dropdown update
  src/App.tsx
  src/components/Header.tsx
  src/components/ui/CopyToClipboard.tsx
  src/components/ui/Header/Avatar.tsx
  src/components/ui/Header/HeaderMenu.tsx
  src/components/ui/Header/MenuItems.tsx
  src/components/ui/Header/index.tsx
  src/components/ui/HeaderDropdown.tsx
  src/components/ui/svg/Clipboard.tsx
  src/components/ui/svg/Connect.tsx
  src/components/ui/svg/Contact.tsx
  src/components/ui/svg/Disconnect.tsx
  src/components/ui/svg/DownArrow.tsx
  src/components/ui/svg/Faq.tsx
  src/components/ui/svg/Logo.tsx
  src/components/ui/svg/Support.tsx
  tailwind.config.js
Labels: ui

#81 User is able to queue a transaction after a successful vote
  src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
  src/components/DAOs/DAO/Proposals/ProposalQueue.tsx
  src/components/ui/ContentBox.tsx
  src/daoData/useDeployDAO.ts
  src/daoData/useProposals.ts
  src/daoData/useQueueTransaction.ts
Labels: data

#84 Update/dao search
  src/components/DAOs/Search/DAOSearch.tsx
  src/components/DAOs/Search/SearchingDAO.tsx
  src/components/ui/forms/InputBox.tsx
  src/hooks/useAddress.ts
  src/hooks/useSearchDao.ts
  src/hooks/useSupportsInterfaces.ts
Labels: bug, ui

#108 Gradients
  public/favicon.ico
  public/logo192.png
  public/logo512.png
Labels: ui
