Repository decentdao/decent-app, pull requests merged in 2022-09, with the labels that each got.

#468 Update/create proposal for reusablity
  src/controller/Modules/index.tsx
  src/pages/GnosisWrapper/index.tsx
  src/pages/GnosisWrapper/routes/index.tsx
  src/pages/ProposalCreate/index.tsx
  src/pages/Proposals/index.tsx
  src/providers/gnosis/GnosisWrapperProvider.tsx
  src/providers/gnosis/hooks/useGnosisWrapper.ts
Labels: enhancement

#464 Gnosis Safe Provider Updates
  package-lock.json
  package.json
  src/controller/Modules/GovernanceController.tsx
  src/controller/Modules/injectors/GnosisGovernanceInjector.tsx
  src/controller/Modules/injectors/TokenGovernanceInjector.tsx
  src/pages/GnosisWrapper/index.tsx
  src/providers/gnosis/GnosisWrapperProvider.tsx
  src/providers/gnosis/helpers/api.spec.ts
  src/providers/gnosis/helpers/api.ts
  src/providers/gnosis/helpers/index.ts
  src/providers/gnosis/hooks/useGnosisApiServices.ts
  src/providers/gnosis/hooks/useGnosisSafeAddress.ts
  src/providers/gnosis/hooks/useGnosisSigner.ts
  src/providers/gnosis/hooks/useGnosisWrapper.ts
  src/providers/gnosis/types/actions.ts
  src/providers/gnosis/types/gnosis.ts
  src/providers/gnosis/types/index.ts
  src/providers/gnosis/types/state.ts
Labels: enhancement, documentation

#469 adds a pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: discussion, documentation

#478 Add sentry
  .env
  .github/workflows/release-ipfs-dev.yaml
  package-lock.json
  package.json
  src/components/ErrorFallback.tsx
  src/components/ui/svg/Alert.tsx
  src/index.tsx
Labels: enhancement

#482 Combine char restrictions
  src/components/DaoCreator/gnosis/GnosisConfig.tsx
  src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx
  src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
  src/components/ui/forms/Input.tsx
Labels: refactor

#475 Dao creator/token supply bn support
  src/components/DaoCreator/gnosis/GnosisConfig.tsx
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/constants/index.ts
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx
  src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
  src/components/ui/forms/Input.tsx
  src/hooks/useCreateDAODataCreator.ts
  src/types/create.ts
Labels: bug, enhancement

#476 Token Allocation BN support
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/hooks/useCreateDAODataCreator.ts
  src/types/tokenAllocation.ts
Labels: enhancement

#487 replaces react.closeElement with context provider
  src/controller/Modules/GovernanceController.tsx
  src/controller/Modules/injectors/GnosisGovernanceInjector.tsx
  src/controller/Modules/injectors/GovernanceInjectorConext.tsx
  src/controller/Modules/injectors/TokenGovernanceInjector.tsx
  src/pages/Transactions/Fractalize/index.tsx
  src/pages/Transactions/Plugins.tsx
Labels: refactor

#477 Parent Token Allocation BigNumber Support
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/hooks/useCreateDAODataCreator.ts
  src/types/create.ts
Labels: enhancement

#491 Implement showing transaction events for classic Treasury
  src/components/Dao/Dashboard.tsx
  src/components/ui/EtherscanTransactionLink.tsx
  src/controller/Modules/TreasuryController.tsx
  src/controller/Modules/injectors/GnosisTreasuryInjector.tsx
  src/controller/Modules/injectors/TreasuryInjector.tsx
  src/pages/Dao/index.tsx
  src/providers/gnosis/hooks/useGnosisEvents.ts
Labels: enhancement, Gnosis Safe

#488 479 Removes Subsidiary Funding dependency
  src/components/DaoCreator/DisplayStepController.tsx
  src/components/DaoCreator/SubsidiaryFunding/FundingOptions.tsx
  src/components/DaoCreator/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/SubsidiaryFunding/types/index.ts
  src/components/DaoCreator/provider/types/index.ts
  src/controller/Modules/GovernanceController.tsx
  src/controller/Modules/injectors/GnosisGovernanceInjector.tsx
  src/controller/Modules/injectors/GnosisTreasuryInjector.tsx
  src/controller/Modules/injectors/TokenGovernanceInjector.tsx
  src/controller/Modules/injectors/TreasuryInjectorContext.tsx
Labels: refactor

#489 subsidary funding to support big numbers
  src/components/DaoCreator/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/SubsidiaryFunding/types/index.ts
  src/controller/Modules/TreasuryController.tsx
  src/controller/Modules/injectors/TokenGovernanceInjector.tsx
Labels: enhancement

#503 Web3 Wallet Provider Update: Connect to local node as signer (test environment)
  .env
  src/contexts/web3Data/Web3Provider.tsx
  src/contexts/web3Data/actions.ts
  src/contexts/web3Data/helpers.ts
  src/contexts/web3Data/hooks/useLIsteners.ts
  src/contexts/web3Data/types.ts
  src/contexts/web3Data/web3Modal.config.ts
  src/hooks/useAddresses.ts
Labels: enhancement
