Repository decentdao/decent-app, pull requests merged in 2022-11, with the labels that each got.

#599 V1 Design | DAO Dashboard Info and Filters
  package-lock.json
  package.json
  src/App.tsx
  src/components/ui/badges/Badge.tsx
  src/i18n/index.ts
  src/i18n/locales/en/badge.json
  src/i18n/locales/en/common.json
  src/i18n/locales/en/dashboard.json
  src/pages/DaoDashboard/Activities/ActivityFilter.tsx
  src/pages/DaoDashboard/Activities/ActivitySort.tsx
  src/pages/DaoDashboard/Activities/index.tsx
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/pages/DaoDashboard/Info/InfoProposals.tsx
  src/pages/DaoDashboard/Info/InfoTreasury.tsx
  src/pages/DaoDashboard/Info/index.tsx
  src/pages/DaoDashboard/index.tsx
  src/routes/DAORoutes.tsx
  src/routes/DAOSubRoutes.tsx
  src/routes/constants/dao.ts
Labels: ui, refactor, V1-Design

#631 testing playwright image container
  .github/workflows/e2e-tests.yml
  docker/webapp/Dockerfile
  playwright.config.ts
Labels: research

#625 Refactor dApp Structure 02 | Delete Components
  src/components/Breadcrumbs.tsx
  src/components/Dao/Dashboard/components/ProposalCard.tsx
  src/components/Dao/Dashboard/components/TransactionCard.tsx
  src/components/Dao/Dashboard/index.tsx
  src/components/Dao/Summary.tsx
  src/components/DaoCreator/provider/hooks/useSteps.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
  src/components/ui/Favorite.tsx
  src/pages/Dao/index.tsx
  src/pages/ProposalCreate/index.tsx
  src/providers/govenor/hooks/useUserProposalValidation.tsx
Labels: refactor

#626 Refactor dApp Structure 03 | Remove Provider and Module Controller
  src/controller/Modules/GovernanceController.tsx
  src/controller/Modules/TreasuryController.tsx
  src/controller/Modules/index.tsx
  src/controller/Modules/injectors/GnosisGovernanceInjector.tsx
  src/controller/Modules/injectors/GnosisTreasuryInjector.tsx
  src/controller/Modules/injectors/GnosisTreasuryInjectorContext.tsx
  src/controller/Modules/injectors/GovernanceInjectorConext.tsx
  src/controller/Modules/injectors/TokenGovernanceInjector.tsx
  src/controller/Modules/injectors/TreasuryInjector.tsx
  src/controller/Modules/injectors/TreasuryInjectorContext.tsx
  src/providers/gnosis/GnosisProvider.tsx
  src/providers/gnosis/GnosisWrapperProvider.tsx
  src/providers/gnosis/helpers/api.spec.ts
  src/providers/gnosis/helpers/api.ts
  src/providers/gnosis/helpers/index.ts
  src/providers/gnosis/helpers/signatures.ts
  src/providers/gnosis/helpers/usul.ts
  src/providers/gnosis/hooks/useGnosis.ts
  src/providers/gnosis/hooks/useGnosisApiServices.ts
  src/providers/gnosis/hooks/useGnosisEvents.ts
  src/providers/gnosis/hooks/useGnosisSafe.ts
  src/providers/gnosis/hooks/useGnosisSafeAddress.ts
  src/providers/gnosis/hooks/useGnosisSigner.ts
  src/providers/gnosis/hooks/useGnosisWrapper.ts
  src/providers/gnosis/hooks/useGnosisWrapperContract.ts
  src/providers/gnosis/hooks/useUsulProposals.ts
  src/providers/gnosis/types/actions.ts
  src/providers/gnosis/types/gnosis.ts
  src/providers/gnosis/types/index.ts
  src/providers/gnosis/types/state.ts
  src/providers/gnosis/types/usul.ts
  src/providers/treasury/TreasuryModuleProvider.tsx
  src/providers/treasury/helpers/api.spec.ts
  src/providers/treasury/helpers/api.ts
  src/providers/treasury/helpers/index.ts
  src/providers/treasury/hooks/useTreasuryAssetsFungible.ts
  src/providers/treasury/hooks/useTreasuryAssetsFungibleFiatAmounts.ts
  src/providers/treasury/hooks/useTreasuryAssetsFungiblePrices.ts
  src/providers/treasury/hooks/useTreasuryAssetsNonFungible.ts
  src/providers/treasury/hooks/useTreasuryEvents.ts
  src/providers/treasury/hooks/useTreasuryModule.ts
  src/providers/treasury/hooks/useTreasuryModuleContract.ts
  src/providers/treasury/models/Web3NFT.ts
  src/providers/treasury/models/Web3Token.ts
  src/providers/treasury/models/index.ts
  src/providers/treasury/types/coingecko.ts
  src/providers/treasury/types/index.ts
  src/providers/treasury/utils/formatFiatAmount.ts
  src/providers/treasury/utils/getMainnetAddress.ts
  src/providers/treasury/utils/index.ts
Labels: refactor

#627 Refactor dApp Structure 04 | Removes/Updates Page Components
  src/pages/GnosisWrapper/index.tsx
  src/pages/GnosisWrapper/routes/index.tsx
  src/pages/Proposals/index.tsx
  src/pages/Transactions/Fractalize/index.tsx
  src/pages/Transactions/Plugins.tsx
  src/pages/Transactions/index.tsx
  src/pages/Treasury/index.tsx
Labels: refactor

#629 Refactor dApp Structure 05 | More mvd cleanup
  src/components/Dao/Dashboard/components/TransactionCard.tsx
  src/components/DaoCreator/ChooseGovernance.tsx
  src/components/DaoCreator/DisplayStepController.tsx
  src/components/DaoCreator/StepButtons.tsx
  src/components/DaoCreator/SubsidiaryFunding/FundingOptions.tsx
  src/components/DaoCreator/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/SubsidiaryFunding/types/index.ts
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/constants/index.ts
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/provider/hooks/useStepName.ts
  src/components/DaoCreator/provider/hooks/useSteps.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/Proposals/ProposalCard.tsx
  src/components/Proposals/UsulProposalsList.tsx
  src/components/menus/DAOSearch/index.tsx
  src/components/ui/StatusBox.tsx
  src/controller/DAOs/DAOController.tsx
  src/controller/Modules/types/actions.ts
  src/controller/Modules/types/enums.ts
  src/controller/Modules/types/index.ts
  src/controller/Modules/types/proposal.ts
  src/controller/Modules/types/state.ts
  src/controller/Modules/utils/index.ts
  src/hooks/useCreateGnosisDAODataCreator.ts
  src/hooks/useDeployDAO.ts
  src/hooks/useIsGnosisSafe.ts
  src/hooks/useSearchDao.ts
  src/pages/DaoCreate/index.tsx
Labels: refactor

#630 Bug | Wallet Disconnect
  .github/workflows/e2e-tests.yml
  docker/webapp/Dockerfile
  playwright.config.ts
  src/contexts/web3Data/utils/injectedProvider.ts
Labels: bug

#628 Refactor dApp Structure 06 | Finale Provider Update
  .github/workflows/e2e-tests.yml
  docker/webapp/Dockerfile
  playwright.config.ts
  src/components/DaoCreator/StepButtons.tsx
  src/contexts/web3Data/utils/injectedProvider.ts
  src/controller/DAOs/DAOController.tsx
  src/hooks/useAddress.ts
  src/hooks/useDeployDAO.ts
  src/hooks/useIsGnosisSafe.ts
  src/hooks/useSearchDao.ts
  src/providers/fractal/FractalProvider.tsx
  src/providers/fractal/constants/actions.ts
  src/providers/fractal/constants/enums.ts
  src/providers/fractal/constants/index.ts
  src/providers/fractal/constants/state.ts
  src/providers/fractal/hooks/useCreateGnosisDAODataCreator.ts
  src/providers/fractal/hooks/useFractal.ts
  src/providers/fractal/hooks/useGnosisApiServices.ts
  src/providers/fractal/hooks/useGnosisEvents.ts
  src/providers/fractal/hooks/useGnosisGovernance.ts
  src/providers/fractal/hooks/useGnosisModuleTypes.ts
  src/providers/fractal/hooks/useSubDAODeploy.ts
  src/providers/fractal/hooks/useUsulProposals.ts
  src/providers/fractal/models/Web3NFT.ts
  src/providers/fractal/models/Web3Token.ts
  src/providers/fractal/models/index.ts
  src/providers/fractal/reducers/gnosis.ts
  src/providers/fractal/reducers/governance.ts
  src/providers/fractal/reducers/index.ts
  src/providers/fractal/reducers/treasury.ts
  src/providers/fractal/types/actions.ts
  src/providers/fractal/types/gnosis.ts
  src/providers/fractal/types/governance.ts
  src/providers/fractal/types/index.ts
  src/providers/fractal/types/state.ts
  src/providers/fractal/types/treasury.ts
  src/providers/fractal/types/usul.ts
  src/providers/fractal/utils/api.spec.ts
  src/providers/fractal/utils/api.ts
  src/providers/fractal/utils/currency.ts
  src/providers/fractal/utils/index.ts
  src/providers/fractal/utils/signatures.ts
  src/providers/fractal/utils/usul.ts
  src/routes/DAOSubRoutes.tsx
  tests/dao/create-parent-dao.spec.ts
  tests/models/FractalPage.ts
Labels: refactor

#638 centers splash screen
  src/App.tsx
  src/constants/common.ts
  src/pages/Home/index.tsx
Labels: ui

#643 V1 Design | Dashboard Activities
  .eslintignore
  src/components/ui/EtherscanLinkAddress.tsx
  src/components/ui/containers/AcitivityBox.tsx
  src/components/ui/containers/InfoBox.tsx
  src/components/ui/loaders/BarLoader.tsx
  src/components/ui/loaders/InfoBoxLoader.tsx
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/en/treasury.json
  src/pages/DaoDashboard/Activities/ActivityCard.tsx
  src/pages/DaoDashboard/Activities/ActivityFilter.tsx
  src/pages/DaoDashboard/Activities/ActivitySort.tsx
  src/pages/DaoDashboard/Activities/ActivityTreasury.tsx
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/pages/DaoDashboard/Info/index.tsx
  src/pages/DaoDashboard/index.tsx
  src/providers/fractal/constants/actions.ts
  src/providers/fractal/constants/state.ts
  src/providers/fractal/reducers/gnosis.ts
  src/providers/fractal/types/actions.ts
  src/providers/fractal/types/gnosis.ts
  src/providers/fractal/types/state.ts
  src/types/activity.ts
  src/types/index.ts
  src/utils/currency.ts
  src/utils/index.ts
  src/utils/time.ts
Labels: ui, V1-Design

#649 V1 | Node Routes and Sidebar Update
  src/components/ui/Sidebar/index.tsx
  src/i18n/locales/en/sidebar.json
  src/pages/Home/index.tsx
  src/routes/DAORoutes.tsx
  src/routes/DAOSubRoutes.tsx
  src/routes/FractalRoutes.tsx
  src/routes/constants/base.ts
  src/routes/constants/dao.ts
Labels: ui, V1-Design

#650 Quickfix | nth-child warning
  src/assets/theme/web3modal.ts
  src/components/menus/AccountDisplay/MenuItems.tsx
Labels: bug

#654 Bug | DAO not loading
  src/pages/Home/index.tsx
  src/pages/Proposals/index.tsx
  src/routes/DAORoutes.tsx
  src/routes/FractalRoutes.tsx
  src/routes/constants/base.ts
  src/routes/constants/dao.ts
  tests/home/visit.spec.ts
  tests/models/DAOCreate.ts
  tests/models/DAOHome.ts
Labels: bug, P1

#652 V1 | DAO Favoriting and Local Storage Update
  src/App.tsx
  src/components/menus/FavoritesMenu/FavoritesList.tsx
  src/components/ui/Favorite.tsx
  src/components/ui/Header/index.tsx
  src/hooks/toasts/useActionToast.tsx
  src/hooks/useFavorites.ts
  src/hooks/useLocalStorage.ts
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/providers/fractal/FractalProvider.tsx
  src/providers/fractal/constants/actions.ts
  src/providers/fractal/constants/state.ts
  src/providers/fractal/hooks/account/useAccount.ts
  src/providers/fractal/hooks/account/useAccountAudit.ts
  src/providers/fractal/hooks/account/useAccountFavorites.ts
  src/providers/fractal/hooks/account/useLocalStorage.ts
  src/providers/fractal/reducers/account.ts
  src/providers/fractal/types/actions.ts
  src/providers/fractal/types/state.ts
Labels: refactor, V1-Design

#663 Package Update | `decent-org/fractal-ui`
  package-lock.json
  package.json
Labels: V1-Design

#656 V1 | Header Clean up
  playwright.config.ts
  src/components/menus/AccountDisplay/MenuButtonDisplay.tsx
  src/components/menus/AccountDisplay/MenuItemButton.tsx
  src/components/menus/AccountDisplay/MenuItemWallet.tsx
  src/components/menus/AccountDisplay/MenuItems.tsx
  src/components/menus/AccountDisplay/index.tsx
  src/components/menus/FavoritesMenu/index.tsx
  src/components/ui/Header/index.tsx
Labels: ui, V1-Design

#668 UI | Nodes Page
  src/components/menus/ManageDAO/ManageDAOMenu.tsx
  src/components/menus/OptionMenu.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/hooks/DAO/useDAOName.ts
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/pages/FractalNodes/NodeLines.tsx
  src/pages/FractalNodes/index.tsx
  src/routes/DAORoutes.tsx
Labels: ui, V1-Design

#675 Refactor | Add Safe SDK for Transaction Service API
  config-overrides.js
  package-lock.json
  package.json
  src/components/DaoCreator/SubsidiaryFunding/types/index.ts
  src/controller/DAOs/DAOController.tsx
  src/pages/Treasury/components/Assets.tsx
  src/pages/Treasury/components/Transactions.tsx
  src/pages/Treasury/hooks/useFormatCoins.tsx
  src/pages/Treasury/hooks/useFormatTransfers.tsx
  src/providers/fractal/FractalProvider.tsx
  src/providers/fractal/constants/actions.ts
  src/providers/fractal/constants/state.ts
  src/providers/fractal/hooks/useGnosisApiServices.ts
  src/providers/fractal/reducers/gnosis.ts
  src/providers/fractal/types/actions.ts
  src/providers/fractal/types/state.ts
  src/providers/fractal/types/treasury.ts
Labels: refactor, Gnosis Safe

#693 Refactor | Add Network Configuration Provider
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/networks/goerli.ts
  src/providers/NetworkConfig/networks/index.ts
  src/providers/NetworkConfig/networks/localhost.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/sepolia.ts
Labels: refactor

#698 Refactor | Config Use
  .env
  src/hooks/useAddresses.ts
  src/hooks/useBuildDAOTx.ts
  src/hooks/useDAOLegacy.ts
  src/hooks/useSafeContracts.ts
  src/index.tsx
  src/providers/fractal/hooks/useDAOLegacy.ts
Labels: refactor

#702 Clean Up | Remove unused secrets
  .github/workflows/release-ipfs-dev.yaml
  .github/workflows/release-ipfs-prod.yaml
Labels: refactor

#697 Update | Add DAO registered name in favorites
  src/components/ui/menus/FavoritesMenu/Favorite.tsx
  src/hooks/DAO/useDAOName.ts
Labels: bug

#709 Implement proposal queuing
  src/components/Proposals/ProposalActions/Queue.tsx
  src/hooks/DAO/proposal/useQueueProposal.ts
  src/i18n/locales/en/transaction.json
Labels: enhancement, ui, Gnosis Safe, V1-Design

#711 Update | Fractal-UI Release v0.1
  package-lock.json
  package.json
  src/components/ConnectWalletToast.tsx
  src/components/DaoCreator/DAODetails.tsx
  src/components/DaoCreator/StepButtons.tsx
  src/components/DaoCreator/SubsidiaryFunding/FundingOptions.tsx
  src/components/DaoCreator/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/gnosis/GnosisConfig.tsx
  src/components/DaoCreator/gnosis/GnosisSignature.tsx
  src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
  src/components/ErrorFallback.tsx
  src/components/ProposalCreate/Essentials.tsx
  src/components/ProposalCreate/Transaction.tsx
  src/components/Proposals/ProposalActions/Execute.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/Proposals/ProposalActions/Queue.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/ui/GnosisSafeLink.tsx
  src/components/ui/Header/PageHeader.tsx
  src/components/ui/ToastContent.tsx
  src/components/ui/forms/Button.tsx
  src/components/ui/forms/Input.tsx
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/modals/DelegateModal.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/hooks/toasts/useActionToast.tsx
  src/hooks/utils/useFormHelpers.tsx
  src/pages/Home/index.tsx
  src/pages/ProposalCreate/index.tsx
  src/pages/ProposalDetails/index.tsx
  src/pages/Proposals/index.tsx
Labels: refactor
