Repository decentdao/decent-app, pull requests merged in 2022-08, with the labels that each got.

#407 fixes broke links
  src/components/ui/Header/MenuItems.tsx
Labels: bug

#408 removed 'focus' outline on buttons
  src/components/ui/forms/Button.tsx
Labels: ui

#409 338 create proposal tokens required
  src/components/ui/ToastContent.tsx
  src/controller/Modules/TokenGovernanceInjector.tsx
  src/controller/Modules/types/proposal.ts
  src/pages/ProposalCreate/index.tsx
  src/pages/Transactions/Plugins.tsx
  src/providers/govenor/GovenorModuleProvider.tsx
  src/providers/govenor/hooks/useGovenorModule.ts
  src/providers/govenor/hooks/useTokenData.ts
  src/providers/govenor/hooks/useUserProposalValidation.tsx
Labels: bug

#419 414 Parent Token Allocation updating during execution
  src/hooks/useCreateDAODataCreator.ts
Labels: bug

#413 412 delegate error state reset
  src/components/Dao/Delegate.tsx
Labels: bug, refactor

#421 Choose Governance DAO Creation Components
  src/components/DaoCreator/ChooseGovernance.tsx
  src/components/DaoCreator/DisplayStepController.tsx
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/constants/index.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/ui/forms/Radio/RadioWithText.tsx
Labels: ui

#431 Update random byte generation code to be way more random
  src/helpers/crypto.ts
Labels: bug

#424 support gnosis configuration
  src/components/DaoCreator/DisplayStepController.tsx
  src/components/DaoCreator/StepButtons.tsx
  src/components/DaoCreator/gnosis/GnosisConfig.tsx
  src/components/DaoCreator/gnosis/GnosisSignature.tsx
  src/components/DaoCreator/index.tsx
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/constants/index.ts
  src/components/DaoCreator/provider/hooks/useDeployDisabled.ts
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
  src/components/DaoCreator/provider/hooks/useSteps.ts
  src/components/DaoCreator/provider/types/index.ts
  src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx
  src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/FundingOptions.tsx
  src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/index.tsx
  src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/types/index.ts
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx
  src/components/ui/forms/Button.tsx
  src/components/ui/forms/Input.tsx
  src/controller/Modules/GovernanceController.tsx
  src/controller/Modules/TokenGovernanceInjector.tsx
  src/controller/Modules/types/proposal.ts
  src/pages/DaoCreate/index.tsx
  src/pages/Transactions/Fractalize/index.tsx
  src/pages/Transactions/Plugins.tsx
Labels: enhancement, ui, refactor, Gnosis Safe

#434 Updates Gnosis Form
  src/components/DaoCreator/gnosis/GnosisConfig.tsx
  src/components/DaoCreator/provider/CreatorProvider.tsx
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
Labels: ui

#440 fix missing types
  src/hooks/useDeployDAO.ts
Labels: bug

#453 BugFIx Token Supply/Amount Error
  src/hooks/useCreateDAODataCreator.ts
Labels: bug

#451 444 Support Rinkeby Testnet
  .env
  src/hooks/useGnosisSafeLink.tsx
Labels: enhancement

#460 Fix SubDAO creation
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx
Labels: bug, refactor

#463 adds case for choose governance step
  src/components/DaoCreator/provider/hooks/useNextDisabled.ts
Labels: bug

#441 update dependencies
  package-lock.json
  package.json
  src/index.tsx
Labels: enhancement

#454 Deploy a Gnosis Safe SubDAO with Token Voting Parent DAO
  src/controller/Modules/TokenGovernanceInjector.tsx
Labels: Gnosis Safe

#466 Buttons off alignment
  src/components/Dao/Delegate.tsx
  src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
  src/components/ui/forms/Button.tsx
  src/pages/Transactions/Plugins.tsx
Labels: bug, ui

#461 Disable Gnosis Safe selection on Sepolia
  src/components/DaoCreator/ChooseGovernance.tsx
  src/components/ui/forms/Radio/RadioWithText.tsx
  src/contexts/web3Data/Web3Provider.tsx
  src/contexts/web3Data/chains.tsx
  src/contexts/web3Data/hooks/useLIsteners.ts
Labels: enhancement, ui, refactor, Gnosis Safe
