Repository decentdao/decent-app, pull requests merged in 2023-02, with the labels that each got.

#948 Refactor | SafeContracts
  .env
  src/assets/images/coin-icon-polygon.svg
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/components/ui/modals/DelegateModal.tsx
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useDeployDAO.ts
  src/hooks/safe/useSafeContracts.ts
  src/hooks/utils/useChainData.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/pages/DaoCreate/index.tsx
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/pages/Treasury/hooks/useFormatCoins.tsx
  src/pages/Treasury/hooks/useFormatTransfers.tsx
  src/pages/Treasury/index.tsx
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUpdateProposalState.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useFreezeData.ts
  src/providers/Fractal/hooks/useGnosisEvents.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useNodes.ts
  src/providers/Fractal/hooks/useVetoContracts.ts
  src/providers/Fractal/utils/api.ts
  src/providers/Fractal/utils/usul.ts
  src/types/contract.ts
  src/utils/dev.ts
Labels: enhancement

#947 Enchancement | Add Polygon network
  .env
  NETWORK_SUPPORT.md
  package-lock.json
  package.json
  src/assets/images/coin-icon-polygon.svg
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/ui/forms/EthAddressInput.tsx
  src/components/ui/links/EtherscanDisplayTransaction.tsx
  src/components/ui/links/EtherscanLinkAddress.tsx
  src/components/ui/links/EtherscanLinkNFT.tsx
  src/components/ui/links/EtherscanLinkToken.tsx
  src/components/ui/links/EtherscanTransactionLink.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/components/ui/modals/DelegateModal.tsx
  src/components/ui/page/Header/Avatar.tsx
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useDAOName.ts
  src/hooks/DAO/useDeployDAO.ts
  src/hooks/safe/useSafeContracts.ts
  src/hooks/utils/useAvatar.ts
  src/hooks/utils/useChainData.ts
  src/hooks/utils/useDisplayName.ts
  src/hooks/utils/useENSName.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/hooks/utils/useSubDomain.tsx
  src/i18n/locales/en/menu.json
  src/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/pages/DaoDashboard/Activities/index.tsx
  src/pages/Treasury/hooks/useFormatCoins.tsx
  src/pages/Treasury/hooks/useFormatTransfers.tsx
  src/pages/Treasury/index.tsx
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useUpdateProposalState.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useFreezeData.ts
  src/providers/Fractal/hooks/useGnosisEvents.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useNodes.ts
  src/providers/Fractal/hooks/useVetoContracts.ts
  src/providers/Fractal/utils/api.ts
  src/providers/Fractal/utils/usul.ts
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/networks/goerli.ts
  src/providers/NetworkConfig/networks/localhost.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/rainbow-kit.config.ts
  src/providers/NetworkConfig/types.ts
  src/types/contract.ts
  src/utils/dev.ts
Labels: enhancement

#985 update queue proposal hook to use correct contract when queuing
  src/hooks/DAO/proposal/useQueueProposal.ts
Labels: bug

#991 Bug: Alert box not full width
  src/components/ProposalCreate/TransactionsAndSubmit.tsx
Labels: bug

#992 Bug: Dao node parent showing 'initiate freeze' option
  src/components/ui/cards/DAOInfoCard.tsx
Labels: bug

#994 Caching | Caches decoded transaction data
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
Labels: bug, enhancement

#999 Refactor | Use Signer when connected for querying events
  src/hooks/DAO/useDAOName.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useVetoContracts.ts
  src/providers/Fractal/utils/usul.ts
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
Labels: enhancement

#1024 Refactor | Mobile Ready Usul Details and Create Proposal
  src/components/ProposalCreate/Transaction.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/ui/containers/ProposalDetailsGrid.tsx
Labels: enhancement

#1019 Refactor | DAO Dashboard and Proposals
  src/components/Activity/ActivityCard.tsx
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/ProposalCreate/Transaction.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/containers/EmptyBox.tsx
  src/components/ui/containers/ProposalDetailsGrid.tsx
  src/components/ui/page/Header/Breadcrumbs.tsx
  src/components/ui/page/Header/PageHeader.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/i18n/locales/en/common.json
  src/pages/Proposals/index.tsx
Labels: enhancement

#1029 Update ukrainian translations
  src/i18n/index.ts
  src/i18n/locales/uk/breadcrumbs.json
  src/i18n/locales/uk/common.json
  src/i18n/locales/uk/daoCreate.json
  src/i18n/locales/uk/dashboard.json
  src/i18n/locales/uk/menu.json
  src/i18n/locales/uk/modals.json
  src/i18n/locales/uk/proposal.json
  src/i18n/locales/uk/proposalMetadata.json
Labels: enhancement

#1033 add injected wallet support
  src/providers/NetworkConfig/rainbow-kit.config.ts
Labels: enhancement

#1037 Bugfix rpc requests reduction
  src/components/Proposals/UsulDetails/index.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
Labels: bug, enhancement, P1

#1013 Refactor | Mobile Ready Navigation
  config-overrides.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/Activity/ActivityCard.tsx
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/ProposalCreate/Transaction.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/containers/EmptyBox.tsx
  src/components/ui/containers/ProposalDetailsGrid.tsx
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/menus/FavoritesMenu/index.tsx
  src/components/ui/page/Header/Breadcrumbs.tsx
  src/components/ui/page/Header/PageHeader.tsx
  src/components/ui/page/Header/index.tsx
  src/components/ui/page/Navigation/NavigationExternalLink.tsx
  src/components/ui/page/Navigation/NavigationLink.tsx
  src/components/ui/page/Navigation/NavigationLinks.tsx
  src/components/ui/page/Navigation/NavigationTooltip.tsx
  src/components/ui/page/Navigation/index.tsx
  src/components/ui/page/Sidebar/index.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/i18n/LanguageSwitcher.tsx
  src/i18n/index.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/navigation.json
  src/i18n/locales/uk/navigation.json
  src/pages/ProposalDetails/index.tsx
  src/pages/Proposals/index.tsx
  tests/models/NavPage.ts
Labels: enhancement

#1039 Bugfix | node page menu ellipsis spacing
  src/components/ui/cards/DAOInfoCard.tsx
Labels: bug

#1038 removes rendering proposals when metadata
  src/pages/ProposalCreate/index.tsx
Labels: bug
