Repository decentdao/decent-app, pull requests merged in 2023-04, with the labels that each got.

#1104 Refactor DataLayer Finale
  app/daos/[daoAddress]/proposals/[proposalNumber]/page.tsx
  app/page.tsx
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/Activity/ActivityGovernance.tsx
  src/components/Activity/ActivityModule.tsx
  src/components/DaoCreator/constants.ts
  src/components/DaoCreator/formComponents/EstablishEssentials.tsx
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/DaoCreator/index.tsx
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/Proposals/ProposalActions/Execute.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/Proposals/ProposalActions/Queue.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/Proposals/ProposalInfo.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/components/Proposals/index.tsx
  src/components/pages/DaoDashboard/Activities/index.tsx
  src/components/pages/DaoDashboard/Info/InfoProposals.tsx
  src/components/ui/badges/Badge.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/components/ui/proposal/ProposalStateBox.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/components/ui/table/TableBodyRow.tsx
  src/components/ui/table/TableHeader.tsx
  src/components/ui/table/TableHeaderItem.tsx
  src/components/ui/table/TableHeaders.tsx
  src/components/ui/table/TableRow.tsx
  src/components/ui/table/index.tsx
  src/constants/strategy.ts
  src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useProposals.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/proposal/useUpdateProposalState.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/graphql/useDAOQuery.ts
  src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
  src/hooks/schemas/proposalCreate/useCreateProposalSchema.ts
  src/hooks/utils/useSafeActivitiesWithState.tsx
  src/hooks/utils/useSafeTransactions.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/governance/action.ts
  src/types/account.ts
  src/types/actions/account.ts
  src/types/actions/governance.ts
  src/types/actions/index.ts
  src/types/actions/node.ts
  src/types/actions/treasury.ts
  src/types/actions/votingToken.ts
  src/types/createDAO.ts
  src/types/daoGovernance.ts
  src/types/daoProposal.ts
  src/types/fractal.ts
  src/types/index.ts
  src/utils/usul.ts
Labels: enhancement

#1105 Refactor BugFix | Proposal Time refactor
  src/components/Proposals/ProposalActions/Execute.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/Proposals/ProposalActions/Queue.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/pages/DAOTreasury/hooks/useSendAssets.ts
  src/components/ui/proposal/ProposalTime.tsx
  src/hooks/DAO/proposal/useQueueProposal.ts
  src/hooks/DAO/proposal/useUpdateProposalState.ts
Labels: bug

#1106 Refactor Bugfix | erc20 account update
  app/daos/[daoAddress]/proposals/page.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
Labels: bug

#1109 Refactor BugFix | Variety
  app/daos/[daoAddress]/proposals/new/page.tsx
  app/daos/[daoAddress]/treasury/page.tsx
  src/components/DaoCreator/constants.ts
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/ProposalCreate/ProposalHeader.tsx
  src/components/ProposalCreate/constants.ts
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/pages/DAOTreasury/hooks/useSendAssets.ts
  src/components/pages/DaoHierarchy/useFetchNodes.tsx
  src/components/ui/forms/CustomNonceInput.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/proposal/useCastVote.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/proposal/useUsul.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
  src/hooks/utils/useSafeActivitiesWithState.tsx
  src/hooks/utils/useSafeTransactions.ts
  src/providers/App/governance/reducer.ts
  src/types/createDAO.ts
  src/types/createProposal.ts
  src/utils/guard.ts
  src/utils/usul.ts
Labels: bug, enhancement

#1114 Refactor | Combine Reducers
  app/daos/[daoAddress]/layout.tsx
  app/page.tsx
  src/components/DaoCreator/formComponents/GnosisMultisig.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/FavoritesMenu/Favorite.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/graphql/index.ts
  src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/loaders/governance/useSafeMultisigProposals.ts
  src/hooks/DAO/loaders/governance/useTokenClaim.ts
  src/hooks/DAO/loaders/useDAOName.ts
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/loaders/useProposals.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useQueueProposal.ts
  src/hooks/DAO/useDAOController.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/combinedReducer.ts
  src/providers/App/governance/action.ts
  src/providers/App/governance/reducer.ts
  src/providers/App/governanceContracts/action.ts
  src/providers/App/governanceContracts/reducer.ts
  src/providers/App/guard/action.ts
  src/providers/App/guard/reducer.ts
  src/providers/App/guardContracts/action.ts
  src/providers/App/guardContracts/reducer.ts
  src/providers/App/node/action.ts
  src/providers/App/node/reducer.ts
  src/providers/ProviderWrapper.tsx
  src/types/fractal.ts
  src/utils/guard.ts
Labels: bug

#1115 Refactor | First Batch @mike's reviews
  app/create/page.tsx
  app/daos/[daoAddress]/new/page.tsx
  src/components/DaoCreator/StepWrapper.tsx
  src/components/DaoCreator/formComponents/GnosisMultisig.tsx
  src/components/DaoCreator/formComponents/UsulTokenAllocation.tsx
  src/components/DaoCreator/formComponents/UsulTokenAllocations.tsx
  src/components/ui/menus/FavoritesMenu/index.tsx
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/uk/daoCreate.json
  src/providers/App/node/reducer.ts
Labels: bug

#1121 Refactor | Next set of various bug fixes
  src/components/pages/DaoHierarchy/DaoNode.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/proposal/useCastVote.ts
  src/hooks/DAO/useDAOName.ts
  src/hooks/utils/useAddress.ts
Labels: bug

#1137 Update | Poll Graph and Safe.
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/utils/useUpdateTimer.tsx
Labels: bug

#1143 Signers custom nonce
  src/components/ProposalCreate/ProposalHeader.tsx
  src/components/pages/ManageSigners/AddSignerModal.tsx
  src/components/pages/ManageSigners/RemoveSignerModal.tsx
  src/components/ui/forms/CustomNonceInput.tsx
Labels: bug

#1142 Feature | Import Existing Token (Create Workflow)
  app/daos/[daoAddress]/proposals/page.tsx
  app/layout.tsx
  src/assets/typechain-types/VotesERC20Wrapper.ts
  src/assets/typechain-types/usul/factories/VotesERC20Wrapper__factory.ts
  src/components/DaoCreator/constants.ts
  src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
  src/components/DaoCreator/formComponents/VotesTokenImport.tsx
  src/components/DaoCreator/formComponents/VotesTokenNew.tsx
  src/components/DaoCreator/hooks/usePrepareFormData.ts
  src/components/ui/forms/InputComponent.tsx
  src/components/ui/forms/Radio/RadioWithText.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/components/ui/modals/UnwrapToken.tsx
  src/components/ui/modals/WrapToken.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalModules.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/safe/useSafeContracts.ts
  src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
  src/hooks/schemas/DAOCreate/useDAOCreateTests.ts
  src/hooks/schemas/common/useValidationAddress.tsx
  src/hooks/utils/useApproval.tsx
  src/i18n/locales/en/common.json
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/en/modals.json
  src/i18n/locales/en/treasury.json
  src/models/AzoriusTxBuilder.ts
  src/models/DaoTxBuilder.ts
  src/providers/App/governance/action.ts
  src/providers/App/governance/reducer.ts
  src/providers/App/node/reducer.ts
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/networks/goerli.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/types/account.ts
  src/types/createDAO.ts
  src/types/fractal.ts
  src/types/network.ts
  src/types/strategyAzorius.ts
Labels: enhancement

#1145 BugFix | Tooltips don't appear in Modals
  src/components/pages/ManageSigners/AddSignerModal.tsx
  src/components/pages/ManageSigners/RemoveSignerModal.tsx
  src/components/ui/badges/Badge.tsx
  src/components/ui/forms/CustomNonceInput.tsx
  src/components/ui/modals/ModalTooltip.tsx
  src/constants/common.ts
  src/i18n/locales/en/modals.json
Labels: bug
