Repository decentdao/decent-app, pull requests merged in 2023-06, with the labels that each got.

#1204 Bugfix variety pack child DAOs
  src/components/Proposals/ProposalSummary.tsx
  src/components/pages/DaoHierarchy/DaoNode.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useLoadDAONode.ts
  src/hooks/DAO/useClawBack.ts
  src/utils/hierarchy.ts
Labels: bug

#1205 Deploy Azorius
  app/daos/[daoAddress]/edit/governance/page.tsx
  src/helpers/crypto.ts
  src/hooks/DAO/useDeployAzorius.ts
  src/i18n/locales/en/proposalMetadata.json
  src/i18n/locales/en/transaction.json
  src/models/AzoriusTxBuilder.ts
  src/models/DaoTxBuilder.ts
  src/models/TxBuilderFactory.ts
Labels: enhancement

#1213 Bug fixes
  app/daos/[daoAddress]/proposals/page.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/hooks/DAO/proposal/useCastVote.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/i18n/locales/en/proposal.json
  src/i18n/locales/uk/proposal.json
Labels: bug

#1219 IPFS Deployment
  .github/workflows/release-ipfs-dev.yaml
  .github/workflows/release-ipfs-prod.yaml
  .github/workflows/release-ipfs-staging.yaml
  .gitignore
  next.config.js
  package.json
  utils/ipfs/postBuild.js
  utils/ipfs/prepareBuild.js
Labels: bug, enhancement

#1221 Add missing graphql assets building
  .github/workflows/release-ipfs-dev.yaml
  .github/workflows/release-ipfs-prod.yaml
  .github/workflows/release-ipfs-staging.yaml
Labels: bug
