Repository decentdao/decent-app, pull requests merged in 2023-03, with the labels that each got.

#1049 ensures proposal details goes to one column on smaller screens
  src/pages/ProposalCreate/index.tsx
Labels: bug

#1050 Bugfix proposal state not updating consistently
  src/components/ui/proposal/ProposalTime.tsx
Labels: bug

#1055 Bugfix | Slight refactor of node hierarchy
  src/components/ui/cards/DAOInfoCard.tsx
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/pages/FractalNodes/DaoNode.tsx
  src/pages/FractalNodes/NodeLines.tsx
  src/pages/FractalNodes/index.tsx
  src/pages/FractalNodes/useFetchNodes.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/actions.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useNodes.ts
  src/providers/Fractal/reducers/gnosis.ts
  src/providers/Fractal/types/actions.ts
  src/providers/Fractal/types/state.ts
Labels: bug, design needed

#1048 Feature | Parent Token Allocation
  src/components/DaoCreator/constants.ts
  src/components/DaoCreator/formComponents/UsulTokenAllocations.tsx
  src/components/DaoCreator/types.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/safe/useSafeContracts.ts
  src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
  src/hooks/schemas/DAOCreate/useDAOCreateTests.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/en/transaction.json
  src/i18n/locales/uk/daoCreate.json
  src/models/DaoTxBuilder.ts
  src/models/TxBuilderFactory.ts
  src/models/UsulTxBuilder.ts
  src/models/helpers/utils.ts
  src/models/types/contracts.ts
  src/pages/DaoDashboard/TokenClaim.tsx
  src/pages/DaoDashboard/index.tsx
  src/providers/Fractal/governance/actions.ts
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/reducer.ts
  src/providers/Fractal/governance/types.ts
  src/providers/Fractal/hooks/useTokenClaim.ts
  src/types/contract.ts
  src/utils/countDecimals.ts
Labels: enhancement

#1061 BugFix? | Adds Usul transaction hash when proposal is executed
  src/components/Proposals/ProposalSummary.tsx
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/utils/usul.ts
Labels: bug, enhancement

#1074 BugFix | DAO Hierarchy
  src/components/ui/cards/DAOInfoCard.tsx
  src/pages/FractalNodes/DaoNode.tsx
  src/pages/FractalNodes/NodeLines.tsx
Labels: bug

#1067 Refactor | Create proposal with Yup and Formik
  src/components/ProposalCreate/ProposalHeader.tsx
  src/components/ProposalCreate/Transaction.tsx
  src/components/ProposalCreate/Transactions.tsx
  src/components/ProposalCreate/TransactionsAndSubmit.tsx
  src/components/ProposalCreate/TransactionsForm.tsx
  src/components/ProposalCreate/UsulMetadata.tsx
  src/components/ProposalCreate/constants.ts
  src/hooks/DAO/proposal/usePrepareProposal.ts
  src/hooks/schemas/proposalCreate/useCreateProposalSchema.ts
  src/pages/ProposalCreate/index.tsx
  src/types/createProposal.ts
  src/types/transaction.ts
  src/utils/crypto.ts
Labels: bug, enhancement

#1060 BugFix | Duplicate intervals setting
  package-lock.json
  package.json
  src/hooks/utils/useUpdateTimer.tsx
Labels: bug

#1082 Bugfix | ENS lookup error causing component not to update
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
Labels: bug

#1084 Refactor - DL | Governance Contracts Hook
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/account/action.ts
  src/providers/App/account/reducer.ts
  src/types/fractal.ts
Labels: enhancement

#1083 Refactor - DL | FractalNode hook
  package-lock.json
  src/hooks/DAO/loaders/useDAOName.ts
  src/hooks/DAO/loaders/useFractalModules.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/account/action.ts
  src/providers/App/account/reducer.ts
  src/types/fractal.ts
Labels: enhancement

#1085 Show daoRegistryName in browser title
  app/daos/[daoAddress]/layout.tsx
  package-lock.json
Labels: bug, enhancement, P3

#1087 Refactor DataLayer | fractal governance
  src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useProposals.ts
  src/hooks/utils/useDecodeTransaction.ts
  src/providers/App/governance/action.ts
  src/providers/App/governance/reducer.ts
  src/providers/App/governanceContracts/action.ts
  src/providers/App/governanceContracts/reducer.ts
  src/providers/Fractal/governance/hooks/useUpdateProposalState.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/providers/Fractal/utils/usul.ts
  src/types/account.ts
  src/types/daoProposal.ts
  src/types/fractal.ts
  src/types/safeGlobal.ts
Labels: enhancement

#1088 Refactor DataLayer | fractal governance multisig
  package-lock.json
  package.json
  src/hooks/DAO/loaders/governance/useSafeMultisigProposals.ts
  src/hooks/DAO/loaders/useProposals.ts
  src/hooks/utils/useSafeTransactions.ts
  src/hooks/utils/useUpdateTimer.tsx
Labels: enhancement

#1089 Refactor DataLayer | fractal treasury
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/providers/App/treasury/action.ts
  src/providers/App/treasury/reducer.ts
  src/types/fractal.ts
Labels: enhancement

#1090 Refactor DataLayer | Freeze Guard and Contracts
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/providers/App/guard/action.ts
  src/providers/App/guard/reducer.ts
Labels: enhancement

#1091 Refactor DataLayer | node hierarchy subgraph
  src/hooks/DAO/loaders/useFractalNode.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/node/reducer.ts
  src/providers/App/nodeHierarchy/action.ts
  src/providers/App/nodeHierarchy/reducer.ts
  src/types/fractal.ts
Labels: enhancement

#1094 Refactor DataLayer | update DAO Dashboard activities
  app/create/page.tsx
  app/daos/[daoAddress]/layout.tsx
  app/layout.tsx
  src/components/Activity/ActivityGovernance.tsx
  src/components/DaoCreator/StepWrapper.tsx
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/DaoCreator/formComponents/UsulTokenAllocations.tsx
  src/components/DaoCreator/index.tsx
  src/components/Proposals/ProposalActions/ProposalAction.tsx
  src/components/pages/DaoDashboard/Activities/ActivityFreeze.tsx
  src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/components/pages/DaoDashboard/Activities/index.tsx
  src/components/pages/DaoDashboard/Info/InfoDAO.tsx
  src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/components/pages/DaoDashboard/Info/InfoProposals.tsx
  src/components/pages/DaoDashboard/Info/InfoTreasury.tsx
  src/components/pages/DaoDashboard/Info/index.tsx
  src/components/pages/DaoDashboard/TokenClaim.tsx
  src/components/ui/page/Header/PageHeader.tsx
  src/components/ui/page/Layout/index.tsx
  src/components/ui/proposal/ProposalTime.tsx
  src/components/ui/utils/Sort.tsx
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/DAO/useDeployDAO.ts
  src/hooks/graphql/useDAOQuery.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/node/action.ts
  src/providers/App/node/reducer.ts
  src/providers/ProviderWrapper.tsx
Labels: enhancement

#1097 Refactor DataLayer | DAO proposals page
  app/daos/[daoAddress]/proposals/page.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/Proposals/index.tsx
  src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/components/pages/DaoDashboard/Activities/index.tsx
  src/components/pages/DaoDashboard/Info/InfoProposals.tsx
  src/hooks/DAO/loaders/governance/useSafeMultisigProposals.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/proposal/useProposals.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/utils/useSafeTransactions.ts
  src/providers/App/AppProvider.tsx
  src/providers/App/governance/reducer.ts
  src/providers/App/node/reducer.ts
  src/types/fractal.ts
Labels: enhancement

#1098 Refactor DataLayer | node hierarchy
  app/daos/[daoAddress]/hierarchy/page.tsx
  src/components/pages/DaoHierarchy/DaoNode.tsx
  src/components/pages/DaoHierarchy/NodeLines.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/menus/OptionMenu.tsx
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/useDAOController.ts
  src/hooks/DAO/useSubDAOData.ts
  src/types/common.ts
  src/types/daoGeneral.ts
Labels: enhancement

#1099 Refactor DataLayer | Update Fractal treasury with new provider
  app/daos/[daoAddress]/treasury/page.tsx
  src/components/pages/DAOTreasury/components/Assets.tsx
  src/components/pages/DAOTreasury/components/Transactions.tsx
  src/components/ui/links/EtherscanLinkAddress.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/hooks/DAO/useDefaultNonce.ts
  src/hooks/utils/useUpdateTimer.tsx
Labels: enhancement

#1100 Refactor DataLayer | Proposal details page
  app/daos/[daoAddress]/proposals/[proposalNumber]/page.tsx
  app/daos/[daoAddress]/proposals/new/page.tsx
  app/daos/[daoAddress]/proposals/page.tsx
  app/daos/[daoAddress]/treasury/page.tsx
  src/components/ProposalCreate/ProposalDetails.tsx
  src/components/Proposals/MultisigProposalDetails/SignerDetails.tsx
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/Proposals/MultisigProposalDetails/index.tsx
  src/components/Proposals/ProposalActions/Vote.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes.tsx
  src/components/Proposals/UsulDetails/index.tsx
  src/components/ui/modals/DelegateModal.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useQueueProposal.ts
  src/providers/App/governanceContracts/action.ts
  src/providers/App/governanceContracts/reducer.ts
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useUpdateProposalState.ts
  src/providers/Fractal/governance/hooks/useUsulProposals.ts
  src/types/fractal.ts
Labels: enhancement

#1102 Refactor DataLayer | Clean up 01
  src/components/Proposals/UsulDetails/index.tsx
  src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/proposal/useUpdateProposalState.ts
  src/hooks/utils/useDecodeTransaction.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/hooks/utils/useSafeTransactions.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/utils/currency.ts
  src/providers/Fractal/utils/index.ts
  src/utils/api.spec.ts
  src/utils/api.ts
  src/utils/crypto.ts
  src/utils/currency.ts
  src/utils/index.ts
  src/utils/safeData.ts
  src/utils/signatures.ts
  src/utils/usul.ts
Labels: enhancement

#1103 Refactor DataLayer | Subdao
  app/daos/[daoAddress]/new/page.tsx
  src/components/Activity/ActivityTreasury.tsx
  src/constants/strategy.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/constants/index.ts
  src/providers/Fractal/constants/state.ts
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/governance/hooks/useSafeMultisigTxs.ts
  src/providers/Fractal/governance/hooks/useVotingContracts.ts
  src/providers/Fractal/governance/reducer.ts
  src/providers/Fractal/hooks/useFractal.ts
  src/providers/Fractal/hooks/useFreezeData.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/hooks/useGnosisEvents.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useTokenClaim.ts
  src/providers/Fractal/hooks/useVetoContracts.ts
  src/providers/Fractal/reducers/account.ts
  src/providers/Fractal/reducers/gnosis.ts
  src/providers/Fractal/reducers/index.ts
  src/providers/Fractal/reducers/treasury.ts
  src/utils/usul.ts
Labels: enhancement
