Repository decentdao/decent-app, pull requests merged in 2023-01, with the labels that each got.

#868 Update | Use `@fractal-framework/fractal-contracts` deployments
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/networks/goerli.ts
  src/providers/NetworkConfig/networks/localhost.ts
  src/providers/NetworkConfig/networks/mainnet.ts
Labels: enhancement

#855 Update | Readd Multisig DAO creation test and setup API Mocking
  docker-compose.yml
  docker/blockchain/Dockerfile
  docker/webapp/Dockerfile
  playwright.config.ts
  src/components/ui/cards/DAOInfoCard.tsx
  src/hooks/safe/useIsSafe.ts
  src/hooks/utils/useUpdateTimer.tsx
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/networks/goerli.ts
  src/providers/NetworkConfig/networks/localhost.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/types.ts
  tests/dao/create-parent-dao.spec.ts
  tests/home/connect-wallet.spec.ts
  tests/home/visit.spec.ts
  tests/models/DAOCreate.ts
  tests/models/DAOHome.ts
  tests/models/DAOTransactions.ts
  tests/models/DaoSafe.ts
  tests/models/FractalPage.ts
  tests/models/HomePage.ts
  tests/models/InputFields.ts
  tests/models/NavPage.ts
  tests/models/mock/GnosisRoutes.ts
  tests/models/mock/NewDAOMockRequests.ts
  tests/models/mock/data/creation.ts
  tests/models/mock/data/testSigners.ts
Labels: enhancement

#870 Bug Fix | Invalid Etherscan Link for TxDetails
  src/components/Proposals/MultisigProposalDetails/TxDetails.tsx
  src/components/ui/EtherscanDisplayTransaction.tsx
  src/i18n/locales/en/proposal.json
  src/i18n/locales/uk/proposal.json
Labels: bug

#889 Bug Fix | update documentation depreciated link
  src/constants/url.ts
  tests/home/visit.spec.ts
Labels: bug

#874 Handle multiSend for Usul proposals
  src/providers/Fractal/utils/api.spec.ts
  src/providers/Fractal/utils/api.ts
  src/providers/Fractal/utils/usul.ts
  src/utils/crypto.ts
Labels: bug, enhancement

#881 Proposal menu item active on proposal details and create proposal pages
  src/components/ui/ProgressBar.tsx
  src/components/ui/Sidebar/index.tsx
  src/pages/ProposalCreate/index.tsx
  src/pages/ProposalDetails/index.tsx
Labels: bug

#890 Automatically favorite the DAO upon deployment
  src/pages/DaoCreate/index.tsx
Labels: enhancement

#891 Search select
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/DAOSearch/index.tsx
Labels: bug

#894 Bugfix | Proposal Execution Refresh
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/i18n/index.ts
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/en/proposalMetadata.json
  src/i18n/locales/uk/daoCreate.json
  src/pages/SubDaoCreate/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/types/state.ts
Labels: bug

#888 Update | Freeze Child DAO option update
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/helpers/freezePeriodHelpers.ts
  src/hooks/DAO/proposal/useExecuteProposal.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useSubDAOData.ts
  src/i18n/index.ts
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/en/proposalMetadata.json
  src/i18n/locales/uk/daoCreate.json
  src/pages/DaoDashboard/Info/InfoDAO.tsx
  src/pages/SubDaoCreate/index.tsx
  src/providers/Fractal/FractalProvider.tsx
  src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
  src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts
  src/providers/Fractal/hooks/useFreezeData.ts
  src/providers/Fractal/hooks/useGnosisApiServices.ts
  src/providers/Fractal/hooks/useGnosisModuleTypes.ts
  src/providers/Fractal/hooks/useVetoContracts.ts
  src/providers/Fractal/types/state.ts
  src/types/dao.ts
Labels: bug, enhancement, P1

#922 Create proposal refresh
  src/hooks/DAO/proposal/useSubmitProposal.ts
Labels: bug

#926 BugFix | Etherscan URL not linked correctly
  src/hooks/utils/useSubDomain.tsx
Labels: bug

#928 Handle decoding error for proposal executable code
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/i18n/locales/en/proposal.json
  src/pages/ProposalCreate/index.tsx
  src/pages/ProposalDetails/index.tsx
  src/types/transaction.ts
  src/utils/crypto.ts
Labels: bug, enhancement, beta feedback

#927 BugFix | fixes new tab tests
  tests/models/FractalPage.ts
  tests/models/HomePage.ts
Labels: bug

#935 Fix DAO loading broken if quickly navigate between pages
  src/components/ui/Sidebar/index.tsx
Labels: bug, beta feedback

#938 Custom nonce
  src/components/ProposalCreate/CustomNonceInput.tsx
  src/components/ProposalCreate/ProposalHeader.tsx
  src/components/ProposalCreate/TransactionsAndSubmit.tsx
  src/components/Proposals/MultisigProposalDetails/TxDetails.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useDefaultNonce.ts
  src/hooks/utils/useParseSafeTxs.tsx
  src/i18n/locales/en/proposal.json
  src/pages/ProposalCreate/index.tsx
  src/pages/SubDaoCreate/index.tsx
  src/pages/Treasury/hooks/useSendAssets.ts
  src/providers/Fractal/governance/types.ts
Labels: enhancement

#946 BugFix: Remove scroll bars on Inputs
  src/components/ProposalCreate/Transaction.tsx
Labels: bug

#941 BugFix: Search Bar Issues
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/hooks/DAO/useSearchDao.ts
Labels: bug

#956 add coinbase wallet support
  src/providers/NetworkConfig/rainbow-kit.config.ts
Labels: enhancement

#957 BugFix: Not using lastest registry event for name
  src/hooks/DAO/useDAOName.ts
Labels: bug
