Repository decentdao/decent-app, pull requests merged in 2023-05, with the labels that each got.

#1148 Add | Max button on inputs
  src/components/ui/forms/BigNumberInput.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/components/ui/modals/UnwrapToken.tsx
  src/components/ui/modals/WrapToken.tsx
  src/i18n/locales/en/common.json
Labels: enhancement

#1149 BugFix | updates number of signers input for better UX
  src/components/DaoCreator/formComponents/GnosisMultisig.tsx
  src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
  src/types/createDAO.ts
Labels: bug

#1151 Bugfix | Clear send asset amount input
  src/components/ui/forms/BigNumberInput.tsx
  src/components/ui/modals/SendAssetsModal.tsx
Labels: bug

#1175 BugFix | Create Child DAO
  src/models/FreezeGuardTxBuilder.ts
Labels: bug

#1178 Bugfix | Blocks and LoadKeys
  next.config.js
  src/components/Proposals/ProposalSummary.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/useFractalFreeze.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useProposals.ts
  src/models/AzoriusTxBuilder.ts
  src/models/DaoTxBuilder.ts
  src/utils/contract.ts
  tsconfig.json
Labels: bug

#1179 Remove ipfs-http-client
  app/daos/[daoAddress]/layout.tsx
  app/layout.tsx
  package-lock.json
  package.json
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/proposal/useCreateProposalTemplate.ts
  src/hooks/DAO/proposal/useRemoveProposalTemplate.ts
  src/providers/App/hooks/useIPFSClient.ts
Labels: bug, P1
