Repository decentdao/decent-app, pull requests merged in 2024-04, with the labels that each got.

#1530 Fix DAO name doesn't update after edit
  src/components/ui/page/Header/PageHeader.tsx
  src/hooks/DAO/useDAOName.ts
  src/hooks/utils/cache/cacheDefaults.ts
Labels: bug

#1583 `Reskin` | App Layout and Header [Part 2]
  src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx
  src/components/ui/menus/AccountDisplay/MenuItemButton.tsx
  src/components/ui/menus/AccountDisplay/MenuItemNetwork.tsx
  src/components/ui/menus/AccountDisplay/MenuItemWallet.tsx
  src/components/ui/menus/AccountDisplay/MenuItems.tsx
  src/components/ui/menus/AccountDisplay/index.tsx
  src/components/ui/menus/DAOSearch/SearchDisplay.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/menus/FavoritesMenu/Favorite.tsx
  src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
  src/components/ui/menus/FavoritesMenu/index.tsx
Labels: re-skin

#1608 Restyle proposals list
  src/components/Activity/ActivityDescription.tsx
  src/components/Activity/ActivityDescriptionGovernance.tsx
  src/components/Proposals/ProposalCard/ProposalCard.tsx
  src/components/Proposals/index.tsx
  src/components/ui/badges/Badge.tsx
  src/components/ui/badges/QuorumBadge.tsx
  src/components/ui/page/Header/Breadcrumbs.tsx
  src/i18n/locales/en/breadcrumbs.json
Labels: enhancement

#1612 `Reskin` create dao page
  src/components/DaoCreator/StepButtons.tsx
  src/components/DaoCreator/StepWrapper.tsx
  src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
  src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenAllocation.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenAllocations.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
  src/components/DaoCreator/formComponents/EstablishEssentials.tsx
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/DaoCreator/formComponents/Multisig.tsx
  src/components/DaoCreator/formComponents/VotesTokenImport.tsx
  src/components/DaoCreator/formComponents/VotesTokenNew.tsx
  src/components/ProposalBuilder/ProposalTransaction.tsx
  src/components/Proposals/ProposalActions/CastVote.tsx
  src/components/pages/DaoSettings/components/Signers/SignersContainer.tsx
  src/components/ui/badges/SupportTooltip.tsx
  src/components/ui/containers/ContentBox/ContentBoxTitle.tsx
  src/components/ui/forms/Radio/RadioWithText.tsx
  src/components/ui/menus/AccountDisplay/MenuItemWallet.tsx
  src/i18n/locales/en/daoCreate.json
  src/i18n/locales/uk/daoCreate.json
  src/pages/HomePage.tsx
Labels: enhancement, re-skin
