Repository decentdao/decent-app, pull requests merged in 2024-10, with the labels that each got.

#2377 Use `fallbackTokenData`
  src/hooks/DAO/loaders/useDecentTreasury.ts
Labels: bug, enhancement, maintenance

#2384 Cancel payment UI
  src/assets/theme/components/input/input.base.ts
  src/components/pages/Roles/DatePickerTrigger.tsx
  src/components/pages/Roles/RolePaymentDetails.tsx
  src/components/pages/Roles/RolesDetailsDrawer.tsx
  src/components/pages/Roles/forms/RoleFormAssetSelector.tsx
  src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
  src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
  src/components/pages/Roles/types.tsx
  src/components/ui/containers/DraggableDrawer.tsx
  src/components/ui/forms/InputBox.tsx
  src/components/ui/modals/ModalBase.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/components/ui/modals/PaymentCancelConfirmModal.tsx
  src/components/ui/utils/DecentDatePicker.tsx
  src/constants/common.ts
  src/hooks/DAO/loaders/useHatsTree.ts
  src/i18n/locales/en/roles.json
  src/pages/DAOController.tsx
  src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
Labels: bug, enhancement

#2386 Configurable fractal module attachment
  src/assets/theme/components/index.ts
  src/assets/theme/components/switch/index.ts
  src/assets/theme/components/switch/switch.base.ts
  src/assets/theme/components/switch/switch.sizes.ts
  src/assets/theme/components/switch/switch.variants.ts
  src/components/DaoCreator/constants.ts
  src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/DaoCreator/hooks/usePrepareFormData.ts
  src/components/DaoCreator/index.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/DAO/useCreateSubDAOProposal.ts
  src/hooks/DAO/useDeployAzorius.ts
  src/i18n/locales/en/daoCreate.json
  src/models/DaoTxBuilder.ts
  src/models/TxBuilderFactory.ts
  src/types/createDAO.ts
  tsconfig.json
Labels: enhancement, maintenance

#2394 Prevent fetching DeFi positions when Moralis does not support it
  src/providers/App/hooks/useBalancesAPI.ts
  src/providers/NetworkConfig/networks/base.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/optimism.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/networks/sepolia.ts
  src/types/network.ts
Labels: bug, enhancement, maintenance

#2389 Consistent empty messages & Mobile Top Nav adjustments
  src/components/ProposalTemplates/index.tsx
  src/components/Proposals/ProposalsList.tsx
  src/components/pages/DAOTreasury/components/Transactions.tsx
  src/components/pages/DaoDashboard/Activities/index.tsx
  src/components/pages/Roles/RolePageCard.tsx
  src/components/pages/Roles/RolesTable.tsx
  src/components/ui/cards/Card.tsx
  src/components/ui/containers/EmptyBox.tsx
  src/components/ui/containers/NoDataCard.tsx
  src/components/ui/menus/AccountDisplay/AccountMenuButton.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/menus/SafesMenu/index.tsx
  src/components/ui/page/Header/Avatar.tsx
  src/components/ui/page/Header/index.tsx
  src/i18n/locales/en/proposal.json
  src/i18n/locales/en/proposalTemplate.json
  src/i18n/locales/en/roles.json
  src/i18n/locales/en/treasury.json
  src/pages/daos/[daoAddress]/edit/governance/index.tsx
  src/pages/daos/[daoAddress]/proposals/[proposalId]/index.tsx
  src/pages/daos/[daoAddress]/roles/edit/index.tsx
  src/pages/daos/[daoAddress]/roles/index.tsx
  src/pages/daos/[daoAddress]/treasury/index.tsx
Labels: bug, enhancement, maintenance

#2391 Fix redirect loaders
  src/main.tsx
  src/router.tsx
Labels: bug, maintenance

#2396 Update toasts
  package-lock.json
  package.json
  src/assets/css/Toast.css
  src/assets/theme/global/index.ts
  src/assets/theme/global/toast.ts
  src/components/DaoCreator/StepButtons.tsx
  src/components/DaoCreator/StepController.tsx
  src/components/ProposalBuilder/index.tsx
  src/components/ui/modals/PaymentWithdrawModal.tsx
  src/hooks/DAO/loaders/useDecentTreasury.ts
  src/hooks/DAO/loaders/useHatsTree.ts
  src/hooks/DAO/proposal/useCastVote.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useClawBack.ts
  src/hooks/utils/useAsyncRequest.ts
  src/hooks/utils/useCopyText.ts
  src/hooks/utils/useCreateRoles.ts
  src/hooks/utils/useTransaction.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/proposal.json
  src/main.tsx
  src/pages/DAOController.tsx
  src/pages/create/index.tsx
  src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx
  src/providers/App/hooks/useIPFSClient.ts
  src/providers/Providers.tsx
Labels: enhancement, maintenance

#2399 Modifying governance for subDAO
  src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
  src/hooks/DAO/useDeployAzorius.ts
  src/hooks/utils/useVotingStrategyAddress.ts
  src/i18n/locales/en/daoCreate.json
  src/pages/daos/[daoAddress]/edit/governance/index.tsx
  src/types/createDAO.ts
Labels: bug, enhancement

#2400 Fix unsaved changes stuck state
  src/components/pages/Roles/forms/RoleFormTabs.tsx
  src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
  src/pages/daos/[daoAddress]/roles/edit/index.tsx
Labels: bug

#2393 Bring Role / Payment editor closer to the design
  src/assets/theme/components/button/button.sizes.ts
  src/assets/theme/components/iconButton/iconButton.sizes.ts
  src/assets/theme/components/tabs/index.ts
  src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
  src/components/DaoCreator/formComponents/GuardDetails.tsx
  src/components/pages/Roles/RoleCard.tsx
  src/components/pages/Roles/RolePaymentDetails.tsx
  src/components/pages/Roles/RolesTable.tsx
  src/components/pages/Roles/forms/RoleFormAssetSelector.tsx
  src/components/pages/Roles/forms/RoleFormInfo.tsx
  src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
  src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
  src/components/pages/Roles/forms/RoleFormSectionTitle.tsx
  src/components/ui/cards/Card.tsx
  src/components/ui/forms/InputComponent.tsx
  src/components/ui/forms/LabelWrapper.tsx
  src/components/ui/icons/Icons.tsx
  src/components/ui/menus/AccountDisplay/AccountMenuButton.tsx
  src/components/ui/menus/AccountDisplay/index.tsx
  src/components/ui/menus/SafesMenu/index.tsx
  src/components/ui/page/Header/Avatar.tsx
  src/components/ui/page/Header/index.tsx
  src/components/ui/page/Layout/index.tsx
  src/components/ui/proposal/ProposalExecutableCode.tsx
  src/constants/common.ts
  src/i18n/locales/en/roles.json
  src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx
  src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
  src/pages/daos/[daoAddress]/roles/index.tsx
  src/pages/home/SafeDisplayRow.tsx
Labels: bug, enhancement

#2412 Attempted fix for flashing while automatically switching chain
  src/i18n/locales/en/common.json
  src/pages/DAOController.tsx
Labels: bug

#2424 `[Whitelisting]` Settings page restructuring
  src/components/DaoCreator/StepController.tsx
  src/components/pages/DaoSettings/DAOSettingsContent.tsx
  src/components/pages/DaoSettings/components/GeneralSettingsContainer.tsx
  src/components/pages/DaoSettings/components/GovernanceContainer.tsx
  src/components/pages/DaoSettings/components/ModulesContainer.tsx
  src/components/pages/DaoSettings/components/PermissionsContainer.tsx
  src/components/pages/DaoSettings/components/SettingsSection.tsx
  src/i18n/locales/en/settings.json
  src/models/FreezeGuardTxBuilder.ts
  src/pages/daos/[daoAddress]/SettingsPage.tsx
  src/providers/NetworkConfig/networks/base.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/optimism.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/networks/sepolia.ts
  src/router.tsx
  src/types/createDAO.ts
Labels: enhancement

#2428 `[Whitelisting]` Settings page design update
  src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/components/pages/DaoSettings/DAOGeneralSettingsPage.tsx
  src/components/pages/DaoSettings/DAOGovernanceSettingsPage.tsx
  src/components/pages/DaoSettings/DAOModulesSettingsPage.tsx
  src/components/pages/DaoSettings/DAOPermissionsSettingsPage.tsx
  src/components/pages/DaoSettings/DAOSettingsContent.tsx
  src/components/pages/DaoSettings/components/GovernanceContainer.tsx
  src/components/pages/DaoSettings/components/MobileSettingsLinks.tsx
  src/components/pages/DaoSettings/components/ModulesContainer.tsx
  src/components/pages/DaoSettings/components/PermissionsContainer.tsx
  src/components/ui/page/Header/NestedPageHeader.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts
  src/i18n/locales/en/settings.json
  src/router.tsx
  src/types/fractal.ts
Labels: bug, enhancement

#2431 `Whitelisting` Multiple voting strategies support
  src/assets/abi/LinearERC20VotingWithHatsProposalCreation.ts
  src/assets/abi/LinearERC721VotingWithHatsProposalCreation.ts
  src/components/pages/Roles/forms/RoleFormInfo.tsx
  src/components/pages/Roles/types.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/loaders/useHatsTree.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
  src/hooks/schemas/roles/useRolesSchema.ts
  src/hooks/utils/useCanUserSubmitProposal.ts
  src/hooks/utils/useMasterCopy.ts
  src/hooks/utils/useVotingStrategiesAddresses.ts
  src/i18n/locales/en/roles.json
  src/pages/daos/[daoAddress]/roles/edit/index.tsx
  src/providers/App/governanceContracts/reducer.ts
  src/store/roles/rolesStoreUtils.ts
  src/store/roles/useRolesStore.ts
  src/types/fractal.ts
Labels: enhancement

#2433 `Whitelisting` voting strategy deployment
  src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
  src/components/pages/Roles/forms/RoleFormInfo.tsx
  src/components/pages/Roles/forms/useRoleFormEditedRole.ts
  src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
  src/hooks/utils/useCreateRoles.ts
  src/models/AzoriusTxBuilder.ts
  src/store/roles/rolesStoreUtils.ts
Labels: bug, enhancement

#2434 `[Whitelisting]` Settings desktop implementation
  src/components/ProposalTemplates/index.tsx
  src/components/pages/DaoSettings/DAOGeneralSettingsPage.tsx
  src/components/pages/DaoSettings/DAOGovernanceSettingsPage.tsx
  src/components/pages/DaoSettings/DAOModulesSettingsPage.tsx
  src/components/pages/DaoSettings/DAOPermissionsSettingsPage.tsx
  src/components/pages/DaoSettings/DAOSettingsContent.tsx
  src/components/pages/DaoSettings/components/GeneralSettingsContainer.tsx
  src/components/pages/DaoSettings/components/GovernanceContainer.tsx
  src/components/pages/DaoSettings/components/MobileSettingsLinks.tsx
  src/components/pages/DaoSettings/components/ModulesContainer.tsx
  src/components/pages/DaoSettings/components/PermissionsContainer.tsx
  src/components/pages/DaoSettings/components/SettingsSection.tsx
  src/components/pages/Roles/RolesDetailsDrawer.tsx
  src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
  src/components/pages/SafeSettings/ERC20TokenContainer.tsx
  src/components/pages/SafeSettings/ERC721TokensContainer.tsx
  src/components/pages/SafeSettings/SettingsNavigation.tsx
  src/components/pages/SafeSettings/Signers/SignersContainer.tsx
  src/components/pages/SafeSettings/Signers/hooks/useAddSigner.ts
  src/components/pages/SafeSettings/Signers/hooks/useRemoveSigner.ts
  src/components/pages/SafeSettings/Signers/modals/AddSignerModal.tsx
  src/components/pages/SafeSettings/Signers/modals/RemoveSignerModal.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/components/ui/page/Header/NestedPageHeader.tsx
  src/constants/routes.ts
  src/i18n/locales/en/settings.json
  src/pages/daos/[daoAddress]/SettingsPage.tsx
  src/pages/daos/[daoAddress]/index.tsx
  src/pages/daos/[daoAddress]/proposal-templates/index.tsx
  src/pages/daos/[daoAddress]/settings/general/index.tsx
  src/pages/daos/[daoAddress]/settings/governance/index.tsx
  src/pages/daos/[daoAddress]/settings/index.tsx
  src/pages/daos/[daoAddress]/settings/modules-and-guard/index.tsx
  src/pages/daos/[daoAddress]/settings/permissions/index.tsx
  src/router.tsx
Labels: bug, enhancement
