Repository decentdao/decent-app, pull requests merged in 2024-11, with the labels that each got.

#2450 BigInt serialization fix
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/main.tsx
  src/types/global.d.ts
  src/utils/polyfills.ts
Labels: bug

#2449 `Whitelisting` settings finalization
  src/assets/theme/custom/icons/PencilWithLineIcon.tsx
  src/assets/theme/custom/icons/WarpcastIcon.tsx
  src/components/Proposals/index.tsx
  src/components/Roles/RolesDetailsDrawer.tsx
  src/components/Roles/RolesDetailsDrawerMobile.tsx
  src/components/Roles/RolesTable.tsx
  src/components/SafeSettings/SettingsNavigation.tsx
  src/components/SafeSettings/SettingsPermissionsStrategyForm.tsx
  src/components/ui/icons/Icons.tsx
  src/components/ui/modals/AddActions.tsx
  src/components/ui/modals/AddStrategyPermissionModal.tsx
  src/components/ui/modals/ConfirmDeleteStrategyModal.tsx
  src/components/ui/modals/ModalBase.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/components/ui/page/Header/NestedPageHeader.tsx
  src/components/ui/page/Navigation/NavigationLinks.tsx
  src/constants/common.ts
  src/constants/routes.ts
  src/hooks/DAO/proposal/useProposals.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/settings.json
  src/pages/dao/roles/SafeRolesPage.tsx
  src/pages/dao/roles/edit/SafeRolesEditPage.tsx
  src/pages/dao/roles/edit/details/SafeRoleEditDetailsPage.tsx
  src/pages/dao/settings/SafeSettingsPage.tsx
  src/pages/dao/settings/SettingsContentBox.tsx
  src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
  src/pages/dao/settings/governance/SafeGovernanceSettingsPage.tsx
  src/pages/dao/settings/modules-and-guard/SafeModulesSettingsPage.tsx
  src/pages/dao/settings/permissions/SafePermissionsCreateProposal.tsx
  src/pages/dao/settings/permissions/SafePermissionsSettingsPage.tsx
  src/pages/dao/treasury/SafeTreasuryPage.tsx
  src/router.tsx
  src/types/createDAO.ts
  src/types/daoTreasury.ts
  src/types/fractal.ts
  src/types/index.ts
  src/types/utils.ts
Labels: bug, enhancement

#2475 remove no wearer throw error
  src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
Labels: bug

#2493 Fix missing DAO creation
  src/providers/NetworkConfig/networks/base.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/optimism.ts
  src/providers/NetworkConfig/networks/polygon.ts
Labels: bug, enhancement, maintenance

#2495 Remove feature flags for termed roles and whitelisting
  .env
  src/components/Roles/RoleDetailsTabs.tsx
  src/components/Roles/forms/RoleFormInfo.tsx
  src/components/Roles/forms/RoleFormMember.tsx
  src/components/SafeSettings/SettingsNavigation.tsx
  src/router.tsx
Labels: maintenance

#2497 Proper menu closing when navigating / selecting date in DatePicker
  src/components/ui/forms/DatePicker.tsx
  src/components/ui/utils/DecentDatePicker.tsx
Labels: bug

#2500 Fix logic for showing withdraw button
  src/components/Roles/RolePaymentDetails.tsx
Labels: bug

#2502 Replace decent date picker with date picker
  src/components/Roles/forms/RoleFormPaymentStream.tsx
  src/components/ui/utils/DecentDatePicker.tsx
Labels: bug, enhancement, maintenance

#2504 Add missing import for datepicker styles
  src/components/ProposalBuilder/ProposalActionCard.tsx
  src/components/ProposalBuilder/index.tsx
  src/components/SafeSettings/SafePermissionsStrategyAction.tsx
  src/components/ui/forms/DatePicker.tsx
  src/components/ui/modals/ConfirmDeleteStrategyModal.tsx
  src/hooks/utils/useCanUserSubmitProposal.ts
  src/pages/dao/settings/permissions/SafePermissionsCreateProposal.tsx
Labels: bug

#2505 Fix spacing
  src/components/SafeSettings/SafePermissionsStrategyAction.tsx
  src/components/ui/modals/ConfirmDeleteStrategyModal.tsx
  src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
  src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
Labels: bug, enhancement, maintenance

#2507 Wrap `getAddressContractType` in `useCallback`
  src/hooks/utils/useAddressContractType.ts
Labels: bug, maintenance
