Repository decentdao/decent-app, pull requests merged in 2024-03, with the labels that each got.

#1383 Caching Cleanup + Timer clearing update
  app/layout.tsx
  src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/components/pages/DaoDashboard/Info/ParentLink.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalModules.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/loaders/useProposals.ts
  src/hooks/utils/useMasterCopy.ts
  src/hooks/utils/useUpdateTimer.tsx
  src/providers/Providers.tsx
Labels: bug

#1435 BugFix: Multisig Deployment Fix
  src/components/DaoCreator/hooks/usePrepareFormData.ts
Labels: bug

#1438 Remove Background Glow
  package-lock.json
  package.json
  src/providers/Providers.tsx
Labels: enhancement

#1443 Fix Treasury Total Format on Dashboard
  src/components/pages/DaoDashboard/Info/InfoTreasury.tsx
Labels: bug

#1432 Implement markdown support for proposal templates and proposal view
  .github/workflows/e2e-tests.yaml
  docker/.env.tests
  docker/webapp/Dockerfile
  package-lock.json
  package.json
  playwright.config.ts
  src/assets/css/Markdown.css
  src/components/Activity/ActivityDescription.tsx
  src/components/Activity/ActivityDescriptionGovernance.tsx
  src/components/CreateProposalTemplate/ProposalTemplateDetails.tsx
  src/components/CreateProposalTemplate/ProposalTemplateMetadata.tsx
  src/components/ProposalCreate/ProposalMetadata.tsx
  src/components/ProposalTemplates/ProposalTemplateCard.tsx
  src/components/Proposals/ProposalInfo.tsx
  src/components/ui/forms/InputComponent.tsx
  src/components/ui/modals/ProposalTemplateModal.tsx
  src/components/ui/proposal/Markdown.tsx
  src/i18n/locales/en/proposal.json
  src/i18n/locales/en/proposalTemplate.json
  src/main.tsx
  src/providers/Providers.tsx
  src/router.tsx
Labels: enhancement

#1467 Upgrade wagmi, viem, web3modal
  .gitignore
  .nvmrc
  package-lock.json
  package.json
  src/components/DaoCreator/formComponents/AzoriusNFTDetail.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
  src/components/pages/DaoHierarchy/useFetchNodes.tsx
  src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx
  src/components/ui/forms/ABISelector.tsx
  src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx
  src/components/ui/menus/AccountDisplay/MenuItemNetwork.tsx
  src/components/ui/menus/AccountDisplay/MenuItemWallet.tsx
  src/components/ui/menus/AccountDisplay/MenuItems.tsx
  src/components/ui/modals/ForkProposalTemplateModal.tsx
  src/components/ui/modals/WrapToken.tsx
  src/graphql/utils/index.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/hooks/DAO/loaders/useLoadDAONode.ts
  src/hooks/DAO/useDAOName.ts
  src/hooks/DAO/useSearchDao.ts
  src/hooks/schemas/DAOCreate/useDAOCreateTests.ts
  src/hooks/utils/useAddress.ts
  src/hooks/utils/useAvatar.ts
  src/hooks/utils/useDisplayName.ts
  src/pages/DAOController.tsx
  src/pages/HomePage.tsx
  src/providers/Ethers/index.tsx
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/web3-modal.config.ts
  src/providers/Providers.tsx
  src/types/network.ts
  vite.config.mts
Labels: bug, maintenance

#1465 Replacing Rainbowkit with Web3Modal
  .gitignore
  .nvmrc
  package-lock.json
  package.json
  src/components/DaoCreator/formComponents/AzoriusNFTDetail.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
  src/components/pages/DaoHierarchy/useFetchNodes.tsx
  src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx
  src/components/ui/forms/ABISelector.tsx
  src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx
  src/components/ui/menus/AccountDisplay/MenuItemNetwork.tsx
  src/components/ui/menus/AccountDisplay/MenuItemWallet.tsx
  src/components/ui/menus/AccountDisplay/MenuItems.tsx
  src/components/ui/modals/ForkProposalTemplateModal.tsx
  src/components/ui/modals/WrapToken.tsx
  src/components/ui/utils/ConnectWalletToast.tsx
  src/graphql/utils/index.ts
  src/hooks/DAO/loaders/useFractalGovernance.ts
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/hooks/DAO/loaders/useLoadDAONode.ts
  src/hooks/DAO/useDAOName.ts
  src/hooks/DAO/useSearchDao.ts
  src/hooks/schemas/DAOCreate/useDAOCreateTests.ts
  src/hooks/utils/useAddress.ts
  src/hooks/utils/useAvatar.ts
  src/hooks/utils/useDisplayName.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/menu.json
  src/i18n/locales/uk/menu.json
  src/pages/DAOController.tsx
  src/pages/HomePage.tsx
  src/providers/Ethers/index.tsx
  src/providers/NetworkConfig/NetworkConfigProvider.tsx
  src/providers/NetworkConfig/rainbow-kit.config.ts
  src/providers/NetworkConfig/testWallet.ts
  src/providers/NetworkConfig/web3-modal.config.ts
  src/providers/Providers.tsx
  src/types/network.ts
  vite.config.mts
Labels: enhancement, maintenance

#1488 BugFix Dev
  package-lock.json
  package.json
Labels: bug

#1493 Fix BigNumber Typo in templates
  src/pages/daos/[daoAddress]/proposal-templates/new/index.tsx
Labels: bug
