Repository decentdao/decent-app, pull requests merged in 2024-08, with the labels that each got.

#2213 Swap fonts from `TT Firs Neue` to `DM Sans`
  index.html
  public/fonts/DMSans-VariableFont_opsz,wght.woff
  public/fonts/DMSans-VariableFont_opsz,wght.woff2
  public/fonts/TT_Firs_Neue_Variable.woff
  public/fonts/TT_Firs_Neue_Variable.woff2
  src/assets/theme/global/toast.ts
  src/assets/theme/index.ts
  src/assets/theme/textStyle/text.styles.tokens.json
Labels: enhancement

#2201 `[roles-0.2.0]` Claim hat stream
  src/assets/abi/SablierV2LockupLinear.ts
  src/components/pages/Roles/RolesDetailsDrawer.tsx
  src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
  src/hooks/streams/useCreateSablierStream.ts
  src/hooks/utils/useCreateRoles.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/roles.json
  src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx
Labels: bug, enhancement

#2247 Normalise `daoSnapshotENS` to lower case
  src/components/DaoCreator/formComponents/EstablishEssentials.tsx
  src/components/Proposals/ProposalInfo.tsx
  src/components/pages/DaoSettings/components/MetadataContainer.tsx
  src/components/ui/cards/DAOInfoCard.tsx
  src/components/ui/cards/DAONodeInfoCard.tsx
  src/components/ui/forms/ABISelector.tsx
  src/hooks/DAO/loaders/snapshot/useSnapshotProposal.ts
  src/hooks/DAO/loaders/snapshot/useSnapshotProposals.ts
  src/hooks/DAO/loaders/snapshot/useSnapshotSpaceName.ts
  src/hooks/DAO/loaders/useLoadDAONode.ts
  src/hooks/DAO/proposal/useCastVote.ts
  src/hooks/DAO/useGetDAOName.ts
  src/hooks/utils/useAvatar.ts
  src/models/DaoTxBuilder.ts
Labels: bug, maintenance

#2272 Fix amount per week
  src/components/pages/Roles/RolePaymentDetails.tsx
Labels: bug

#2277 `BugFix` Don't convert `bigint` directly to `number`
  src/hooks/schemas/roles/useRolesSchema.ts
Labels: bug

#2233 Sablier proposal builder
  package-lock.json
  package.json
  src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
  src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
  src/components/ProposalBuilder/ProposalDetails.tsx
  src/hooks/utils/useCreateRoles.ts
  src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx
  src/router.tsx
Labels: enhancement, user-feedback

#2273 Fix streams creation for roles with existing payments, fix editing payments
  src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
  src/hooks/schemas/roles/useRolesSchema.ts
  src/hooks/streams/useCreateSablierStream.ts
  src/hooks/utils/useCreateRoles.ts
  src/i18n/locales/en/roles.json
  src/store/roles/rolesStoreUtils.ts
Labels: bug

#2290 Fix logic for showing option for initiating freeze
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
Labels: bug

#2297 Adjust styling for search input and header navigation
  src/assets/theme/components/input/input.base.ts
  src/assets/theme/components/input/input.sizes.ts
  src/assets/theme/components/numberInput/numberInput.sizes.ts
  src/assets/theme/components/textarea/textarea.sizes.ts
  src/components/ui/menus/AccountDisplay/index.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/menus/SafesMenu/SafesList.tsx
  src/components/ui/menus/SafesMenu/index.tsx
Labels: enhancement

#2310 Update eslint packages and node version
  .nvmrc
  package-lock.json
  package.json
  src/models/FreezeGuardTxBuilder.ts
Labels: bug, maintenance

#2311 Readme update & cleanup
  README.md
Labels: maintenance

#2316 Center TopErrorFallback in da middle of the screen
  src/components/ui/utils/TopErrorFallback.tsx
Labels: bug, design

#2309 Proper active payments count `EVERYWHERE`
  src/components/pages/Roles/RolesTable.tsx
  src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
  src/components/pages/Roles/forms/RoleFormTabs.tsx
  src/components/pages/Roles/forms/useRoleFormEditedRole.tsx
  src/hooks/DAO/loaders/useHatsTree.ts
  src/hooks/streams/useCreateSablierStream.ts
  src/hooks/utils/useCreateRoles.ts
  src/i18n/locales/en/roles.json
  src/pages/daos/[daoAddress]/roles/index.tsx
Labels: bug, enhancement
