Repository decentdao/decent-app, pull requests merged in 2024-05, with the labels that each got.

#1678 `Reskin` - root reskin review bug fixes
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
  src/components/DaoCreator/formComponents/AzoriusTokenAllocations.tsx
  src/components/ProposalBuilder/ProposalDetails.tsx
  src/components/ProposalBuilder/ProposalTransaction.tsx
  src/components/ProposalBuilder/ProposalTransactionsForm.tsx
  src/components/ProposalTemplates/index.tsx
  src/components/Proposals/ProposalInfo.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes/ProposalERC721VoteItem.tsx
  src/components/Proposals/SnapshotProposalDetails/SnapshotProposalSummary.tsx
  src/components/pages/DAOTreasury/components/Assets.tsx
  src/components/pages/DaoDashboard/Activities/ActivityFreeze.tsx
  src/components/pages/DaoDashboard/ERC20Claim.tsx
  src/components/pages/DaoDashboard/Info/DaoSpecificMetadataHeader.tsx
  src/components/ui/badges/QuorumBadge.tsx
  src/components/ui/containers/TitledInfoBox.tsx
  src/components/ui/icons/FavoriteIcon.tsx
  src/components/ui/links/AddressCopier.tsx
  src/components/ui/links/EtherscanLinkBase.tsx
  src/components/ui/menus/AccountDisplay/NetworkSelector.tsx
  src/components/ui/menus/AccountDisplay/WalletMenu.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
  src/components/ui/menus/OptionMenu/index.tsx
  src/components/ui/modals/SendAssetsModal.tsx
  src/components/ui/page/Header/PageHeader.tsx
  src/components/ui/page/Layout/index.tsx
  src/components/ui/page/Navigation/NavigationLink.tsx
  src/components/ui/page/Navigation/NavigationLinks.tsx
  src/components/ui/utils/CeleryButtonWithIcon.tsx
  src/components/ui/utils/Divider.tsx
  src/components/ui/utils/TopErrorFallback.tsx
  src/i18n/LanguageSwitcher.tsx
  src/pages/404.tsx
  src/pages/LoadingProblem.tsx
  src/pages/daos/[daoAddress]/treasury/index.tsx
Labels: bug, enhancement, re-skin

#1751 Update og:image
  public/images/hero_image.png
Labels: re-skin

#1753 `Reskin` update languages menu positioning
  src/i18n/LanguageSwitcher.tsx
Labels: re-skin

#1763 Bugfix graphql type
  src/hooks/DAO/loaders/useFractalNode.ts
  src/hooks/DAO/loaders/useLoadDAONode.ts
Labels: bug

#1776 `Reskin` - remove module transactions
  src/components/Activity/ActivityDescriptionModule.tsx
  src/components/Activity/ActivityModule.tsx
  src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
  src/components/pages/DaoDashboard/Activities/index.tsx
  src/hooks/utils/useSafeTransactions.ts
  src/i18n/locales/en/dashboard.json
  src/i18n/locales/uk/dashboard.json
Labels: re-skin

#1779 `Reskin`- hover effect on parent link
  src/components/pages/DaoDashboard/Info/DaoInfoHeader.tsx
  src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
  src/components/pages/DaoDashboard/Info/ParentLink.tsx
Labels: bug, re-skin

#1783 Restyle "Wrong network"
  src/components/ui/icons/Icons.tsx
  src/pages/HomePage.tsx
  src/pages/LoadingProblem.tsx
Labels: re-skin

#1803 Swap out `getUsdBalances` with `getBalances`
  src/components/pages/DAOTreasury/hooks/useFormatCoins.tsx
  src/components/pages/DAOTreasury/hooks/useSendAssets.ts
  src/components/ui/modals/SendAssetsModal.tsx
  src/components/ui/modals/Stake.tsx
  src/hooks/DAO/loaders/useFractalTreasury.ts
  src/providers/App/hooks/usePriceAPI.ts
  src/providers/App/hooks/useSafeAPI.ts
  src/types/createDAO.ts
  src/types/daoTreasury.ts
  src/types/fractal.ts
  src/utils/numberFormats.ts
Labels: bug

#1835 `BugFix` 1827 Safe Created DAO Page doesn't work
  src/hooks/DAO/loaders/useFractalNode.ts
  src/providers/App/node/action.ts
Labels: bug

#1832 Update useSendAssets to use encodeFunctionData for ERC20 transfer
  package-lock.json
  package.json
  src/components/pages/DAOTreasury/hooks/useSendAssets.ts
Labels: bug

#1843 `Enhancement` Draggable Safe Drawer
  src/pages/home/AllSafesDrawer.tsx
Labels: enhancement

#1856 `Reskin` - mobile side nav
  src/components/ui/menus/DAOSearch/index.tsx
  src/components/ui/page/Header/index.tsx
  src/components/ui/page/Layout/index.tsx
  src/components/ui/page/Navigation/NavigationLink.tsx
  src/components/ui/page/Navigation/NavigationLinks.tsx
  src/constants/common.ts
  src/i18n/locales/en/navigation.json
Labels: re-skin
