Repository decentdao/decent-app, pull requests merged in 2024-02, with the labels that each got.

#1374 Fix Multiple Re-render caused by `useEffect`
  src/components/pages/DaoHierarchy/DaoNode.tsx
Labels: bug

#1373 Voting Strategies Upgrade + Master Copy Caching
  app/daos/[daoAddress]/proposals/new/page.tsx
  src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
  src/hooks/DAO/loaders/useFractalGuardContracts.ts
  src/hooks/DAO/loaders/useFractalModules.ts
  src/hooks/DAO/loaders/useGovernanceContracts.ts
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
  src/hooks/DAO/useDeployAzorius.ts
  src/hooks/utils/cache/cacheDefaults.ts
  src/hooks/utils/useGetMasterCopyAddress.ts
  src/utils/azorius.ts
Labels: enhancement

#1375 Align deployment of Safe to be of same version as Safe UI-deployed and having fallback handler attached
  src/components/Proposals/MultisigProposalDetails/TxActions.tsx
  src/hooks/DAO/proposal/useSubmitProposal.ts
  src/hooks/DAO/useBuildDAOTx.ts
  src/hooks/DAO/useDeployAzorius.ts
  src/hooks/safe/useSafeContracts.ts
  src/models/AzoriusTxBuilder.ts
  src/models/DaoTxBuilder.ts
  src/models/FreezeGuardTxBuilder.ts
  src/models/MultisigTxBuilder.ts
  src/models/TxBuilderFactory.ts
  src/models/helpers/fractalModuleData.ts
  src/models/helpers/safeData.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/networks/sepolia.ts
  src/types/contract.ts
  src/types/fractal.ts
  src/types/network.ts
Labels: bug, enhancement
