Repository decentdao/decent-app, pull requests merged in 2024-09, with the labels that each got.

#2321 `Bugfix` | EditStreams
  src/components/pages/Roles/RolePaymentDetails.tsx
  src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
  src/components/pages/Roles/types.tsx
  src/hooks/DAO/loaders/useHatsTree.ts
  src/hooks/utils/useCreateRoles.ts
  src/store/roles/rolesStoreUtils.ts
  src/store/roles/useRolesStore.ts
Labels: bug

#2333 Process roles serially
  src/hooks/streams/useCreateSablierStream.ts
  src/hooks/utils/useCreateRoles.ts
Labels: maintenance

#2336 Do not allow clicking(aka editing) soft-deleted roles
  src/components/pages/Roles/RoleCard.tsx
  src/components/pages/Roles/RolesTable.tsx
Labels: bug, enhancement

#2350 Snapshot proposal breakdown and votes fixes
  src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVoteItem.tsx
  src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx
Labels: bug, enhancement

#2352 Some additional validation and UI fixes for Sablier Proposal builder
  src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx
Labels: bug, enhancement
