Repository decentdao/decent-app, pull requests merged in 2025-01, with the labels that each got.

#2649 `[ENG-86]` Try decoding transactions with `viem`'s `decodeFunctionData` when Safe Decoder fails
  src/components/ui/forms/ABISelector.tsx
  src/hooks/utils/useSafeDecoder.tsx
Labels: bug, enhancement

#2661 Fix getting / showing voting weight on NFT DAO proposals
  public/images/hero_image.png
  src/assets/css/Toast.css
  src/components/DaoCreator/formComponents/EstablishEssentials.tsx
  src/components/DaoCreator/index.tsx
  src/components/Proposals/ProposalSummary.tsx
  src/components/Proposals/ProposalVotes/context/VoteContext.tsx
  src/components/ui/menus/DAOSearch/index.tsx
  src/constants/common.ts
  src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
  src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
  src/pages/create/SafeCreatePage.tsx
  src/utils/azorius.ts
Labels: bug

#2647 `[ENG-65]` `[ENG-66]` Create example templates for Transfer, Airdrop and Sablier stream creation
  src/components/ProposalBuilder/ProposalActionCard.tsx
  src/components/ProposalTemplates/ExampleTemplateCard.tsx
  src/components/Roles/forms/RoleFormCreateProposal.tsx
  src/components/ui/modals/AirdropModal.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/constants/routes.ts
  src/hooks/DAO/useSendAssetsActionModal.tsx
  src/hooks/utils/useCreateRoles.ts
  src/hooks/utils/useGetSafeName.ts
  src/hooks/utils/useResolveENSName.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/modals.json
  src/i18n/locales/en/proposal.json
  src/i18n/locales/en/proposalTemplate.json
  src/pages/dao/proposal-templates/SafeProposalTemplatesPage.tsx
  src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
  src/pages/dao/treasury/SafeTreasuryPage.tsx
  src/providers/NetworkConfig/networks/base.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/optimism.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/networks/sepolia.ts
  src/providers/NetworkConfig/web3-modal.config.ts
  src/types/network.ts
  src/types/proposalBuilder.ts
  src/utils/dao/prepareSendAssetsActionData.ts
Labels: enhancement

#2646 `[ENG-65]` `[ENG-66]` - example proposal templates + unified UX for Sablier PB and general PB
  src/components/ProposalBuilder/ProposalActionCard.tsx
  src/components/ProposalBuilder/ProposalBuilder.tsx
  src/components/ProposalBuilder/ProposalDetails.tsx
  src/components/ProposalBuilder/ProposalMetadata.tsx
  src/components/ProposalBuilder/ProposalStream.tsx
  src/components/ProposalBuilder/ProposalStreams.tsx
  src/components/ProposalBuilder/ProposalTransaction.tsx
  src/components/ProposalBuilder/ProposalTransactions.tsx
  src/components/ProposalBuilder/ProposalTransactionsForm.tsx
  src/components/ProposalBuilder/StepButtons.tsx
  src/components/ProposalBuilder/constants.ts
  src/components/ProposalBuilder/index.tsx
  src/components/ProposalTemplates/ExampleTemplateCard.tsx
  src/components/Roles/forms/RoleFormCreateProposal.tsx
  src/components/ui/cards/SendAssetsActionCard.tsx
  src/components/ui/modals/AirdropModal.tsx
  src/components/ui/modals/ModalProvider.tsx
  src/constants/routes.ts
  src/hooks/DAO/useSendAssetsActionModal.tsx
  src/hooks/utils/useCreateRoles.ts
  src/i18n/locales/en/common.json
  src/i18n/locales/en/modals.json
  src/i18n/locales/en/proposal.json
  src/i18n/locales/en/proposalTemplate.json
  src/pages/dao/proposal-templates/SafeProposalTemplatesPage.tsx
  src/pages/dao/proposal-templates/new/SafeCreateProposalTemplatePage.tsx
  src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
  src/pages/dao/proposals/new/SafeProposalCreatePage.tsx
  src/pages/dao/proposals/new/sablier/SafeSablierProposalCreatePage.tsx
  src/pages/dao/treasury/SafeTreasuryPage.tsx
  src/providers/NetworkConfig/networks/base.ts
  src/providers/NetworkConfig/networks/mainnet.ts
  src/providers/NetworkConfig/networks/optimism.ts
  src/providers/NetworkConfig/networks/polygon.ts
  src/providers/NetworkConfig/networks/sepolia.ts
  src/providers/NetworkConfig/web3-modal.config.ts
  src/types/network.ts
  src/types/proposalBuilder.ts
  src/utils/dao/prepareSendAssetsActionData.ts
Labels: bug, enhancement, maintenance

#2700 `[ENG-176]` Termed Payments following user to different DAO
  src/store/roles/useRolesStore.ts
  src/types/roles.tsx
Labels: bug

#2701 `[ENG-177]` Existing payment causing validation error
  src/hooks/schemas/roles/useRolesSchema.ts
Labels: bug
